<p>
<ul id="mostBookedCarousel" class="first-and-second-carousel jcarousel-skin-tango">
<?php if (isset($this->error)) { ?>
    <p>An error was encountered in search.</p>
<?php } 
elseif ($this->mostBookedListings != null) { 
    foreach($this->mostBookedListings as $mostBookedData) {
        $image = $this->zvImage()->getFirstListingImage($this->baseUrl(), $mostBookedData);
        $title = $this->escape($mostBookedData->title);
        $url = $this->baseUrl().$this->escape($mostBookedData->id);
        if( strlen($title) > VILLA_NAME_SMALL_SIZE )
             $title = substr($title,0,(VILLA_NAME_SMALL_SIZE-3)).'...';
        $item = 
                '<li>' .
                '<img src="' .
                $image .
                '" height="70" width="110"/>'.
                '<p>'.
                $title .
                '</p>'.
                '<span><img src="'.
                $this->baseUrl('/images/symbl_rupee.jpg') .
                '" alt="Indian Rupee" />' .
                $mostBookedData->rate['daily'].
                '</span>' .
                '</li>'
                ;
        $items[] = $item; 
        $urls[] = $url;
    }
}
else { ?>
    <p>No results were returned from search.</p>
<?php } ?> 
</ul>
</p>
<script type="text/javascript">
	mostBookedData = [
 		<?php for ($i=0; $i<count($items); $i++) {?> 
			<?php if ($i> 0) {?>
				, <?php //do not remove the ',' (comma) ?>
			<?php }?>
			'<?php echo '<a href="/list?id='.$urls[$i].'"/a>'. $items[$i] . '</a>';?>'
		<?php }?>
	];
</script>

 