<p>
	<ul id="mostBookedCarousel" class="first-and-second-carousel jcarousel-skin-tango">
		<?php if (isset($this->error)) { ?>
			<p>An error was encountered in search.</p>
				<?php } elseif ($this->mostbookedlistings != null) { ?>
					<?php foreach($this->mostbookedlistings as $mostBookedData) : ?>
					<?php $image = $this->zvImage()->getFirstListingImage($this->baseUrl(), $mostBookedData);?>	
						<li><img src="<?php echo $image;?>" height="70" width="110">
							<p>
							<?php 
								if( strlen($this->escape($mostBookedData->title)) > VILLA_NAME_SMALL_SIZE )
									echo substr($this->escape($mostBookedData->title),0,(VILLA_NAME_SMALL_SIZE-3)).'...';
								else
									echo $this->escape($mostBookedData->title);
							?>
							</p>
							<span><img src="<?php echo $this->baseUrl();?>/images/symbl_rupee.jpg" alt="Indian Rupee" /><?php echo $this->escape(0+$mostBookedData->rate['daily']);?></span>
						</li>
 					<?php endforeach; ?>
 				<?php } else {?>
			<p>No results were returned from search.</p>
		<?php } ?> 
	</ul>
</p>