<?php include_once("ZipVilla/TypeConstants.php");?>

<div class="search_homebx">
    <input class="search_home defaultText" type="text" name="query" id="query" size="73" title="Where do you want to go?" autocomplete="off" value=""/>
	<input class="submit_search" type="submit" value="" onclick="validate_default();return true;" />
	<div style="clear:both;"><p id="set_location" style="display:none;margin-top:10px;text-align:center;color:#CC3366;">Please enter a town or city.</p></div>
		<div class="floatleft"><label for="checkin"><br/>Check in<br/>
			<input class="input_home defaultText checkin" title="<?php echo DATE_FORMAT;?>" type="text" size="10" name="check_in"  value="<?php echo $this->checkin;?>"/></label>
		</div>
		<div class="floatleft"><label for="checkout"><br/>Check out<br/>
			<input class="input_home defaultText checkout" title="<?php echo DATE_FORMAT;?>" type="text" size="10" name="check_out" value="<?php echo $this->checkout;?>"/></label>
		</div>
		<div class="floatleft">
			<label for="guests"><br/>Guests<br/>
                <select class="v_dropdwon_bg l_dropdwon_bg" style="margin-top:7px;height:30px;vertical-align:center;" id="guests" name="guests">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                        <option>6</option>
                        <option>7</option>
                        <option>8</option>
                        <option>9</option>
                        <option value="10">10+</option>
                </select>
				<!-- <input size="2" class="guest_home" id="guests" name="guests" />  -->
			</label>
		</div>
		<input type="hidden" id="page" name="page" value="1" />
</div>
    
