<p>
<ul id="mostViewedCarousel" class="first-and-second-carousel jcarousel-skin-tango">
<?php if (isset($this->error)) { ?>
    <p>An error was encountered in search.</p>
<?php } 
elseif ($this->mostViewedListings != null) {
    foreach($this->mostViewedListings as $mostViewedData) {
        $image = $this->zvImage()->getFirstListingImage($this->baseUrl(), $mostViewedData);
        $title = $this->escape($mostViewedData->title);
        if( strlen($title) > VILLA_NAME_SMALL_SIZE )
            $title = substr($title,0,(VILLA_NAME_SMALL_SIZE-3)).'...';
        $item = '<li><img src="' .
                $image .
                '" height="70" width="110"/>'.
                '<p>'.
                $title .
                '</p>'.
                '<span><img src="'.
                $this->baseUrl('/images/symbl_rupee.jpg') .
                '" alt="Indian Rupee" />' .
                $mostViewedData->rate['daily'].
                '</span>' .
                '</li>';
        $items[] = $item; 
    }
}
else { ?>
    <p>No results were returned from search.</p>
<?php } ?> 
</ul>
</p>
<script type="text/javascript">
    mostViewedData = [
    <?php for ($i=0; $i<count($items); $i++) {?>
        <?php if ($i> 0) {?>
            ,'<?php echo $items[$i];?>'
        <?php }else {?>
            '<?php echo $items[$i];?>'
        <?php }?>
    <?php }?>
    ];
</script>