<?php
$this->title = "Accomodations";
$this->headTitle($this->title);
$mapHelper = $this->map();
?>
	<p>
		<a
			href="<?php echo $this->url(array('controller'=>'index', 'action'=>'add'));?>">Add
			new accomodation</a>
	</p>
	
 <?php if ($this->listings == null) { ?>
	<p>There are no accomodations to show.</p>
 <?php } else {?>
<table>
	<tr>
		<th>Type</th>
		<th>Street</th>
		<th>City</th>
		<th>State</th>
		<th>Bedrooms</th>
		<th>Max Guests</th>
		<th>Amenities</th>
		<th>&nbsp;</th>
	</tr>

  <?php foreach($this->listings as $listing) : ?>
		<tr>
			<td><?php echo $this->escape($listing->type);?></td>
			<td><?php echo $this->escape($listing->address['street_name']);?></td>
			<td><?php echo $this->escape($listing->address['city']);?></td>
			<td><?php echo $this->escape($listing->address['state']);?></td>
			<td><?php echo $this->escape($listing->bedrooms);?></td>
			<td><?php echo $this->escape($listing->guests);?></td>

        <?php $eoptions = $listing->amenities;?>
        	<td><?php if ($eoptions != null) { foreach ($eoptions as $k => $v) { echo "$k -&gt; \"$v\" <br/>"; } }?></td>
        	<td> 
            	<a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'edit', 'id'=>$listing->id));?>">Edit</a>
            	<a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'delete', 'id'=>$listing->id));?>">Delete</a>
        	</td>
		</tr>
  <?php endforeach; ?>
</table>
<script type="text/javascript">
   <?php echo $mapHelper->setMapFromDbListings($this->listings, 'zvMapInfo');?>
</script>
<?php }?>
