<?php
    $this->title = "Accomodations";
    $this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'add'));?>">Add new accomodation</a></p>
<?php if ($this->listings == null) { ?>
<p>There are no accomodations to show.</p>
<?php } else {?>
<table>
    <tr>
        <th>Type</th>
        <th>State</th>
        <th>&nbsp;</th>
    </tr>
<?php foreach($this->listings as $listing) : ?>
    <tr>
        <td><?php echo $this->escape($listing->type);?></td>
        <td><?php echo $this->escape($listing->address['state']);?></td>
        <td> 
            <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'edit', 'id'=>$listing->id));?>">Edit</a>
            <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'delete', 'id'=>$listing->id));?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<?php }?>
