<?php $this->headTitle('Create New Listing'); ?>
<?php $this->layout()->setLayout('account');?>
<?php 
      $id = '';
      if ((!isset($this->listing) || ($this->listing == null))) {
?>
        <div class="error_msg2">
        <p>Please fill in basic property information by clicking <a href="/account/new?nextpage=1">here</a> before coming to this page.</p>
        </div>
<?php } else { 
        $id=$this->listing->id;
?>
<div class="l_property_details v_property_details"><!--Property details sections starts here-->
    <h1>Tell us more...</h1>
    <div class="sub_title"><p>You are only a few steps away from listing your property at Zipvilla.<br />Tell us more about your place and complete your listing.</p></div>
    <div style="margin-bottom:20px;" class="detials_form"><!--detials_form-->
        <h2>Availability and pricing</h2>
        <p>View availability and set special pricing for specific dates.</p>
        <div class="slct_mnth"><!--form select-->
            <div class="slct_mnth_dropdwn">
                <form action="">
                    <p style="width:auto;"><strong>Select Month</strong></p>
                    <select class="dropdown_sm" name="per night">
                    <?php $firstOfMonth = strtotime(date('Y-m',time()));
                    for ($i=0; $i<=12;$i++) { 
                        $d = date('M  Y', strtotime('+'.$i.' months', $firstOfMonth)); ?>
                        <option value="<?php echo $d;?>"><?php echo $d; ?></option>
                    <?php }?>
                    </select>
                </form>
            </div>
        </div>  <!--form select ends-->
        <div id="loadergif"></div>
        <div class="calendar1">
        </div>
        <div class="refer1">
            <div class="wrpr_keys">
                <div class="available key">&nbsp;</div>
                <div class="key-text">Available</div>
            </div>
            <div class="wrpr_keys">
                <div class="unavailable key">&nbsp;</div>
                <div class="key-text">Unavailable</div>
            </div>
            <div class="wrpr_keys">
                <div class="past key">&nbsp;</div>
                <div class="key-text">Past</div>
            </div>
        </div>
    </div><!--detials_form ends here-->
    <div class="wrpr_btn_savencont">
        <form name="part3" method="get">
            <INPUT class="btn_savencont" type="submit" value="" />
            <input type="hidden" name="nextpage" value="4" />
        </form>
    </div>
</div><!--Property details ends here-->
<div class="l_property_right v_property_right">
    <div>
    <h4 class="l_link_back_page v_link_back_page"><a href="#">Back to Listings</a></h4>
    <h2>Need help? Call us:</h2>
    <p>+91-80-4115-0200<br />+91-80-4115-0400</p>
    </div>
    <div class="property_right_nav">
        <ul>
            <li><a href="/account/new?nextpage=1&id=<?php echo $id;?>">Basic Information</a></li>
            <li><a href="/account/new?nextpage=2&id=<?php echo $id;?>">Property Details</a></li>
            <li><a href="#" onclick="return false;" class="active1">Calendar</a></li>
            <li style="border-bottom:none;"><a href="/account/new?nextpage=4&id=<?php echo $id;?>">Photos and Videos</a></li>
        </ul>
    </div>
</div>
<?php } ?>

                                        