<?php $this->headTitle('Create New Listing'); ?>
<?php $this->layout()->setLayout('account');?>
<?php if (isset($this->alert)) {?>
<div class="error_msg2">
    <p><?php echo $this->alert;?></p>
</div>
<?php }?>
<div class="l_property_details v_property_details"><!--Property details sections starts here-->
    <h1>Tell us more...</h1>
    <div class="sub_title"><p>You are only a few steps away from listing your property at Zipvilla.<br />Tell us more about your place and complete your listing.</p></div>
    <div class="detials_form"><!--detials_form-->
        <form>
            <h2>Availability and pricing</h2>
            <p>View availability and set special pricing for specific dates.</p>
            <div class="slct_mnth"><!--form select-->
                <div class="slct_mnth_dropdwn">
                    <form action="">
                    <p style="width:auto;"><strong>Select Month</strong></p>
                    <select class="dropdown_sm" name="per night">
                        <option value="opt1">January <span>2012</span></option>
                        <option value="opt2">February <span>2012</span></option>
                        <option value="opt3">March <span>2012</span></option>
                        <option value="opt4">April <span>2012</span></option>
                        <option value="opt1">May <span>2012</span></option>
                        <option value="opt2">June <span>2012</span></option>
                        <option value="opt3">July <span>2012</span></option>
                        <option value="opt4">August <span>2012</span></option>
                        <option value="opt1">September <span>2012</span></option>
                        <option value="opt2">October <span>2012</span></option>
                        <option value="opt3">November <span>2012</span></option>
                        <option value="opt4">December <span>2012</span></option>
                    </select>
                    </form>
                </div>
            </div><!--form select ends-->
            <div class="calendar1">
                <table>
                    <tbody>
                        <tr>
                            <th>SUN</th>
                            <th>MON</th>
                            <th>TUE</th>
                            <th>WEN</th>
                            <th>THU</th>
                            <th>FRI</th>
                            <th>SAT</th>
                        </tr>
                        <tr>
                            <td><span>1</span></td>
                            <td><span>2</span></td>
                            <td><span>3</span></td>
                            <td><span>4</span></td>
                            <td><span>5</span></td>
                            <td class="avail"><span>6</span></td>
                            <td class="nobrdr"><span>7</span></td>
                        </tr>
                        <tr>
                            <td class="avail"><span>8</span><br>
                                <div class="today_price">Rs.4,500</div>
                            </td>
                            <td class="avail"><span>9</span></td>
                            <td class="avail"><span>10</span></td>
                            <td class="avail"><span>11</span></td>
                            <td class="avail"><span>12</span></td>
                            <td><span>13</span></td>
                            <td class="nobrdr avail"><span>14</span></td>
                        </tr>
                        <tr>
                            <td class="unavail"><span>15</span></td>
                            <td class="unavail"><span>16</span></td>
                            <td class="unavail"><span>17</span></td>
                            <td class="unavail"><span>18</span></td>
                            <td class="unavail"><span>19</span></td>
                            <td class="unavail"><span>20</span></td>
                            <td class="nobrdr unavail"><span>21</span></td>
                        </tr>
                        <tr>
                            <td><span>22</span></td>
                            <td class="avail"><span>23</span><br />
                                <div class="today_price">Rs.24,500</div>
                            </td>
                            <td><span>24</span></td>
                            <td><span>25</span></td>
                            <td><span>26</span></td>
                            <td><span>27</span></td>
                            <td class="nobrdr"><span>28</span></td>
                        </tr>
                        <tr>
                            <td class="unavail"><span>29</span></td>
                            <td class="unavail"><span>30</span></td>
                            <td class="unavail"><span>31</span></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="refer1">
                <div class="wrpr_keys">
                    <div class="available key">&nbsp;</div>
                    <div class="key-text">Available</div>
                </div>
                <div class="wrpr_keys">
                    <div class="unavailable key">&nbsp;</div>
                    <div class="key-text">Unavailable</div>
                </div>
                <div class="wrpr_keys">
                    <div class="past key">&nbsp;</div>
                    <div class="key-text">Past</div>
                </div>
            </div>
        </form>
    </div><!--detials_form ends here-->
</div><!--Property details ends here-->
<div class="l_property_right v_property_right">
    <div>
    <h4 class="l_link_back_page v_link_back_page"><a href="#">Back to Listings</a></h4>
    <h2>Need help? Call us:</h2>
    <p>+91-80-4115-0200<br />+91-80-4115-0400</p>
    </div>
    <div class="property_right_nav">
        <ul>
            <li><a href="#">Basic Information</a></li>
            <li><a href="#">Property Details</a></li>
            <li><a href="#" class="active1">Calendar</a></li>
            <li style="border-bottom:none;"><a href="#">Photos and Videos</a></li>
        </ul>
    </div>
</div>


                                        