<?php $this->headTitle('Create New Listing'); ?>
<?php $this->layout()->setLayout('account');?>
<?php 
      $id = '';
      if ((!isset($this->listing) || ($this->listing == null))) {
?>
        <div class="error_msg2">
        <p>Please fill in basic property information by clicking <a href="/account/new?nextpage=1">here</a> before coming to this page.</p>
        </div>
<?php } else { 
        $id=$this->listing->id;
?>
<div class="l_property_details v_property_details"><!--Property details sections starts here-->
    <h1>Tell us more...</h1>
    <div class="sub_title"><p>You are only a few steps away from listing your property at Zipvilla.<br />Tell us more about your place and complete your listing.</p></div>
    <div style="margin-bottom:20px;" class="detials_form"><!--detials_form-->
        <h2>Availability and pricing</h2>
        <p>View availability and set special pricing for specific dates.</p>
        <div class="slct_mnth"><!--form select-->
            <div class="slct_mnth_dropdwn">
                <form action="">
                    <p style="width:auto;"><strong>Select Month</strong></p>
                    <select class="dropdown_sm" name="per night">
                    <?php $firstOfMonth = strtotime(date('Y-m',time()));
                    for ($i=0; $i<=12;$i++) { 
                        $d = date('M  Y', strtotime('+'.$i.' months', $firstOfMonth)); ?>
                        <option value="<?php echo $d;?>"><?php echo $d; ?></option>
                    <?php }?>
                    </select>
                </form>
            </div>
        </div>  <!--form select ends-->
        <div id="loadergif"></div>
        <div id="calendar1" class="calendar1" style="cursor: pointer;">
        </div>
        <div class="refer1">
            <div class="wrpr_keys">
                <div class="available key">&nbsp;</div>
                <div class="key-text">Available</div>
            </div>
            <div class="wrpr_keys">
                <div class="unavailable key">&nbsp;</div>
                <div class="key-text">Unavailable</div>
            </div>
            <div class="wrpr_keys">
                <div class="past key">&nbsp;</div>
                <div class="key-text">Past</div>
            </div>
        </div>
    </div><!--detials_form ends here-->
    <div class="wrpr_btn_savencont">
        <form name="part3" method="get">
            <INPUT class="btn_savencont" type="submit" value="" />
            <input type="hidden" name="nextpage" value="4" />
            <input type="hidden" name="id" value="<?php echo $id;?>" />
        </form>
    </div>
</div><!--Property details ends here-->
<div class="l_property_right v_property_right">
    <div>
    <h4 class="l_link_back_page v_link_back_page"><a href="/account">Back to Listings</a></h4>
    <h2>Need help? Call us:</h2>
    <p>+91-80-4115-0200<br />+91-80-4115-0400</p>
    </div>
    <div class="property_right_nav">
        <ul>
            <li><a href="/account/new?nextpage=1&id=<?php echo $id;?>">Basic Information</a></li>
            <li><a href="/account/new?nextpage=2&id=<?php echo $id;?>">Property Details</a></li>
            <li><a href="#" onclick="return false;" class="active1">Calendar</a></li>
            <li style="border-bottom:none;"><a href="/account/new?nextpage=4&id=<?php echo $id;?>">Photos and Videos</a></li>
        </ul>
    </div>
</div>
<div id="boxes">
  <div id="lb_edit_calendar" class="lb_window_zv" style="height: 100px; width: 300px; background:none;">
    <div class="close cboxClose3"></div>
    <div id="fb-root"></div>
    <div class="wrapper"><!--outer wrapper to fix the width-->
        <div class="edit_cal">
            <form id="update_calendar" action="" method="get">
                <h2><?php echo $this->listing->title;?></h2>
                <div class="box">
                    <div id="lb_error"></div>
                    <div><label for="from">From</label><input class="from checkin" type="text" size="15" id="from" name="from"/></div>
                    <div><label for="to">To</label><input class="to checkout" type="text" id="to" size="15" name="to"/></div>
                    <div style="height:35px;">
                        <label for="available">Available?</label>
                            <input type="radio" name="available" value="yes" />Yes
                            <input type="radio" name="available" value="no" checked="yes"/>No
                    </div>
                    <div><label for="price">Price</label><input class="to" type="text" id="price" size="15" name="price" value="<?php echo $this->listing->rate['daily'];?>"/></div>
                </div>
                <p class="btn_cancel close"><a href="#">Cancel</a></p>
                <input class="submit" type="submit" onclick="updateCalendar(); return false;" value="">
            </form>
        </div>
    </div><!-- wrapper ends here -->
  </div>
</div> 
<div id="mask_zv"></div>
<?php } ?>

                                        