<?php $this->headTitle('Upload Images'); ?>
<?php $this->layout()->setLayout('account');?>
<?php include_once('ZipVilla/TypeConstants.php');?>
<?php 
	$id = '';
	if ((!isset($this->listing) || ($this->listing == null))) {
?>
	<div class="error_msg2">
		<p>Please fill in basic property information by clicking <a href="/account/new?nextpage=1">here</a> before coming to this page.</p>
	</div>
<?php } else { 
	$id=$this->listing->id;
    if ($this->listing instanceof Application_Model_Listings) {
        $listingtype = PRODUCTION_LISTING;
    } else {
        $listingtype = PRE_LISTING;
    }
	?>
	<div class="l_property_details v_property_details"><!--Property details sections starts here-->
		<h1>Zipvilla Image Upload</h1>
        <div class="sub_title">
            <p>You are only a few steps away from listing your property at Zipvilla.<br/>
               Select the pictures for your property to complete your listing.</p>
        </div>
        <?php 
            $images = $this->listing->images;
            $images = $images == null ? array() : $images;
            $imageprefix = $this->zvImage()->getImagePathPrefix('', $this->listing);
        ?>
        <div class="detials_form list_img">
            <ul id="gallery">
                <?php foreach($images as $image) {
                    $image = trim($image);
                    $showref = preg_replace('/[^a-zA-Z0-9]/', '', $image);
                ?>
                    <li id="<?php echo $showref;?>"><img src="<?php echo $this->baseUrl($imageprefix.'/'.$image);?>" alt="resort" /><p><a href="#" onclick="dropImage('<?php echo $this->listing->id;?>', '<?php echo $listingtype;?>', '<?php echo $image;?>', '<?php echo $showref;?>'); return false;">Remove</a></p></li>
                <?php } ?>
            </ul>
        </div>
		<div class="detials_form"><!--detials_form-->
    		    <form id="fileupload" action="" method="POST" enctype="multipart/form-data">
                    <div class="row fileupload-buttonbar">
                        <div class="span7">
                            <span class="btn btn-success fileinput-button" style="clear:both;">
                                <div class="btn_newlist"><img src="/images/btn_select_image.jpg" alt="Select Image" /></div><input type="file" name="files[]" multiple="true" accept="image/*" onchange="showSelectedFiles(this);return false;">
                            </span>
                        </div>
                        <div class="btn_newlist"><a href="#" onclick="uploadImages('<?php echo $id;?>', '<?php echo $listingtype;?>');return false;"><img src="/images/btn_uplaod.jpg" alt="Upload" /></a></div>
                    </div>
                </form>
                <div class="wrap_list">
    			<?php for ($i = 0; $i < FILE_UPLOAD_MAX; $i++) {?>
    			    <div id="show<?php echo $i;?>" class="listing" style="display:none;">
        			<div id="villa<?php echo $i;?>" class="villa_image"><img id="img<?php echo $i;?>" src="" alt="resort" /></div>
                        <div class="image_file">
                            <h4 id="name<?php echo $i;?>"></h4>
                        </div>
                        <div class="image_size">
                            <h4 id="size<?php echo $i;?>"></h4>
                        </div>
                        <input type="hidden" name="sendfile" value="<?php echo $i;?>"/>
                        <div class="remove">
                                <a href="#" onclick="deleteImage(<?php echo $i;?>);return false;"><img src="/images/btn_reject.jpg" alt="Remove" /></a>
                        </div>
                        <div id="msg<?php echo $i;?>" class="msg"></div>
                    </div>
    			<?php } ?>
                </div>
                <div id="info"></div> 
        </div><!--detials_form ends here-->
	</div><!--Property details ends here-->
	<div class="l_property_right v_property_right">
		<div>
			<h4 class="l_link_back_page v_link_back_page"> <a href="/account?show=listings">Back to Listings</a> </h4>
			<h2>Need help? Call us:</h2>
			<p>	+91-80-XXXX-XXXX<br />+91-80-XXXX-XXXX</p>
		</div>
		<div class="property_right_nav">
			<ul>
				<li><a href="/account/new?nextpage=1&id=<?php echo $id;?>">Basic Information</a></li>
				<li><a href="/account/new?nextpage=2&id=<?php echo $id;?>">Property Details</a></li>
				<li><a href="/account/new?nextpage=3&id=<?php echo $id;?>">Calendar</a></li>
				<li style="border-bottom: none;"><a	href="#" onclick="return false;" class="active1">Photos and Videos</a></li>
			</ul>
		</div>
	</div>
        
<?php } ?>

                                        