<?php $this->headTitle('Create New Listing - Upload Images'); ?>
<?php $this->layout()->setLayout('account');?>
<?php 
	$id = '';
	if ((!isset($this->listing) || ($this->listing == null))) {
?>
	<div class="error_msg2">
		<p>Please fill in basic property information by clicking <a href="/account/new?nextpage=1">here</a> before coming to this page.</p>
	</div>
<?php } else { 
	$id=$this->listing->id;?>
	<div class="l_property_details v_property_details"><!--Property details sections starts here-->
		<h1>Zipvilla Image Upload</h1>
			<div class="sub_title"><p>You are only a few steps away from listing your property at Zipvilla.<br />
				Select the pictures for your property to complete your listing.</p></div>
				<div class="detials_form"><!--detials_form-->
        
        <!--
        /*
         * jQuery File Upload Plugin 6.2
         * https://github.com/blueimp/jQuery-File-Upload
         *
         * Copyright 2010, Sebastian Tschan
         * https://blueimp.net
         *
         * Licensed under the MIT license:
         * http://www.opensource.org/licenses/MIT
        */
        -->
        <div class="navbar navbar-fixed-top">
        
        </div>
        <div class="container">
	        <div class="page-header">

					</div>
						<p>
						Please click on <strong>+ Add Files</strong> to select the images of your property 
						that you would like to display on <strong>ZipVilla</strong>.
						</p><br>
					<!-- The file upload form used as target for the file upload widget -->
					<form id="fileupload" action="../upload/php/" method="POST" enctype="multipart/form-data">
						<!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
						<div class="row fileupload-buttonbar">
							<div class="span7">
								<!-- The fileinput-button span is used to style the file input field as button -->
								<span class="btn btn-success fileinput-button">
									<span><i class="icon-plus icon-white"></i> Add files...</span>
									<input type="file" name="files[]" multiple>
								</span>
								<button type="submit" class="btn btn-primary start">
									<i class="icon-upload icon-white"></i> Start upload
								</button>
								<button type="reset" class="btn btn-warning cancel">
									<i class="icon-ban-circle icon-white"></i> Cancel upload
								</button>
								<button type="button" class="btn btn-danger delete">
									<i class="icon-trash icon-white"></i> Delete
								</button>
								<input type="checkbox" class="toggle">
							</div>
							<div class="span5">
								<!-- The global progress bar -->
								<div class="progress progress-success progress-striped active fade">
									<div class="bar" style="width:0%;"></div>
								</div>
							</div>
						</div>
						<br>

						<!-- The table listing the files available for upload/download -->
						<table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>
					</form>
        	<br>
					<div class="well">
						<h3>Hints:</h3>
		        <ul>
			        <li>The maximum file size for uploads \is <strong>5 MB</strong> </li>
			        <li>Only image files (<strong>JPG, GIF, PNG</strong>) are allowed.</li>
			        <li>You can <strong>drag &amp; drop</strong> files from your desktop on this webpage with Google Chrome, Mozilla Firefox and Apple Safari.</li>
		        </ul>
					</div>
				</div>

        <!-- modal-gallery is the modal dialog used for the image gallery -->
				<div id="modal-gallery" class="modal modal-gallery hide fade">
					<div class="modal-header">
						<a class="close" data-dismiss="modal">&times;</a>
						<h3 class="modal-title"></h3>
					</div>
					<div class="modal-body"><div class="modal-image"></div></div>
					<div class="modal-footer">
						<a class="btn btn-primary modal-next">Next <i class="icon-arrow-right icon-white"></i></a>
						<a class="btn btn-info modal-prev"><i class="icon-arrow-left icon-white"></i> Previous</a>
						<a class="btn btn-success modal-play modal-slideshow" data-slideshow="5000"><i class="icon-play icon-white"></i> Slideshow</a>
						<a class="btn modal-download" target="_blank"><i class="icon-download"></i> Download</a>
					</div>
        </div>
  
        <!-- Error messages for the upload/download templates -->
        <script>
	        var fileUploadErrors = {
	            maxFileSize: 'File is too big',
	            minFileSize: 'File is too small',
	            acceptFileTypes: 'Filetype not allowed',
	            maxNumberOfFiles: 'Max number of files exceeded',
	            uploadedBytes: 'Uploaded bytes exceed file size',
	            emptyResult: 'Empty file upload result'
	        };
        </script>
  
        <!-- The template to display files available for upload -->
        <script id="template-upload" type="text/html">
        alert("in 1");
        {% for (var i=0, files=o.files, l=files.length, file=files[0]; i<l; file=files[++i]) { %}
            <tr class="template-upload fade">
        <td class="preview"><span class="fade"></span></td>
                <td class="name">{%=file.name%}</td>
                <td class="size">{%=o.formatFileSize(file.size)%}</td>
                {% if (file.error) { %}
                    <td class="error" colspan="2"><span class="label label-important">Error</span> {%=fileUploadErrors[file.error] || file.error%}</td>
                {% } else if (o.files.valid && !i) { %}
                    <td>
                        <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
                    </td>
                    <td class="start">{% if (!o.options.autoUpload) { %}
                        <button class="btn btn-primary">
                            <i class="icon-upload icon-white"></i> Start
                        </button>
                    {% } %}</td>
                {% } else { %}
                    <td colspan="2"></td>
                {% } %}
                <td class="cancel">{% if (!i) { %}
                    <button class="btn btn-warning">
                        <i class="icon-ban-circle icon-white"></i> Cancel
                    </button>
                {% } %}</td>
            </tr>
        {% } %}
        </script>
        <!-- The template to display files available for download -->
        <script id="template-download" type="text/html">
        alert("in 2");
        {% for (var i=0, files=o.files, l=files.length, file=files[0]; i<l; file=files[++i]) { %}
            <tr class="template-download fade">
                {% if (file.error) { %}
                    <td></td>
                    <td class="name">{%=file.name%}</td>
                    <td class="size">{%=o.formatFileSize(file.size)%}</td>
                    <td class="error" colspan="2"><span class="label label-important">Error</span> {%=fileUploadErrors[file.error] || file.error%}</td>
                {% } else { %}
                    <td class="preview">{% if (file.thumbnail_url) { %}
                        <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery"><img src="{%=file.thumbnail_url%}"></a>
                    {% } %}</td>
                    <td class="name">
                        <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}">{%=file.name%}</a>
                    </td>
                    <td class="size">{%=o.formatFileSize(file.size)%}</td>
                    <td colspan="2"></td>
                {
        % } %}
                <td class="delete">
                    <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
                        <i class="icon-trash icon-white"></i> Delete
        </button>
        <input type="checkbox" name="delete" value="1">
        </td>
        </tr>
        {
        % } %}
        </script>
        
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

        <!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
        <script src="../js/vendor/jquery.ui.widget.js"></script>
        <!-- The Templates and Load Image plugins are included for the FileUpload user interface -->
        <script src="../js/tmpl.min.js"></script>
        <script src="http://blueimp.github.com/JavaScript-Load-Image/load-image.min.js"></script>
        <!-- Bootstrap JS and Bootstrap Image Gallery are not required, but included for the demo -->
        <script src="http://blueimp.github.com/cdn/js/bootstrap.min.js"></script>
        <script src="http://blueimp.github.com/Bootstrap-Image-Gallery/js/bootstrap-image-gallery.min.js"></script>
        <!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
        <script src="../js/jquery.iframe-transport.js"></script>
        <!-- The basic File Upload plugin -->
        <script src="../js/jquery.fileupload.js"></script>
        <!-- The File Upload image processing plugin -->
        <script src="../js/jquery.fileupload-ip.js"></script>        
        <!-- The File Upload user interface plugin -->
        <script src="../js/jquery.fileupload-ui.js"></script>
        <!-- The main application script -->
        <script src="../js/main.js"></script>
        <!-- The XDomainRequest Transport is included for cross-domain file deletion for IE8+ -->
        <!--[if gte IE 8]><script src="js/cors/jquery.xdr-transport.js"></script><![endif]-->
        
				</div><!--detials_form ends here-->
	</div><!--Property details ends here-->
	<div class="l_property_right v_property_right">
		<div>
			<h4 class="l_link_back_page v_link_back_page"> <a href="/account?show=listings">Back to Listings</a> </h4>
			<h2>Need help? Call us:</h2>
			<p>	+91-80-4115-0200<br />+91-80-4115-0400 </p>
		</div>
		<div class="property_right_nav">
			<ul>
				<li><a href="/account/new?nextpage=1&id=<?php echo $id;?>">Basic Information</a></li>
				<li><a href="#" onclick="return false;" class="active1">Property Details</a></li>
				<li><a href="/account/new?nextpage=3&id=<?php echo $id;?>">Calendar</a></li>
				<li style="border-bottom: none;"><a	href="#">Photos and Videos</a></li>
			</ul>
		</div>
	</div>
        
<?php } ?>

                                        