<?php $this->headTitle('Account Dashboard'); ?>
<?php $this->layout()->setLayout('account');?>
<?php if (isset($this->alert)) {?>
<div class="error_msg2">
    <p><?php echo $this->alert;?></p>
</div>
<?php }?>
<div class="l_search_results v_search_results"><!--Search result sections starts here-->
    <div id="tabs" class="ui-tabs"><!--tabs-->
        <ul>
            <li><a href="#tabs-1">Bookings</a></li>
            <li><a href="#tabs-2">Listings</a></li>
            <li><a href="#tabs-3">Account</a></li>
        </ul>
        <div id="tabs-1">
        </div>
        <div id="tabs-2">
        </div>
        <div id="tabs-3">
            <div class="tab_content">
            </div>
        </div>
        
    </div>
    <div id="loadergif" display="none"><img src="<?php echo $this->baseUrl('/css/loader.gif');?>"/></div>
</div>
<?php
if ($this->user != null) { 
    $name = $this->user->firstname . ' ' . $this->user->lastname;
    $image = $this->user->image != null ? $this->user->image : 'default_user_image.jpg';
    $email = $this->user->emailid;
}
?>
<div class="l_right_side_panel v_right_side_panel">
<?php if ($this->user != null) { ?>
    <div class="db_profile">
        <div class="profile">
            <div class="profile_photo"><img src="<?php echo $this->baseUrl('/images/users/'.$image);?>" alt="image" /></div>
            <h2><?php echo $name;?></h2>
            <p><?php echo $email;?></p>
            <div class="edit_prfl">
                <span><img src="images/ico_edit.jpg" alt="edit" /></span>
                <h4><a href="#">EDIT PROFILE</a></h4>
            </div>
        </div>
    </div><!--db_profile ends-->
<?php } ?>
    <div class="right_nav">
        <ul>
            <li><a href="<?php echo $this->baseUrl('/account/new?nextpage=1');?>">List your property</a></li>
            <li><a href="#">Manage favorites</a></li>
        </ul>
    </div>
</div>
                                        