<?php $this->headTitle('Create New Listing - Property Details'); ?>
<?php $this->layout()->setLayout('account');?>

<?php if (isset($this->alert)) {?>
<div class="error_msg2">
    <p><?php echo $this->alert;?></p>
</div>
<?php }?>
<div class="l_property_details v_property_details"><!--Property details sections starts here-->
    <h1>Tell us more...</h1>
    <div class="sub_title"><p>You are only a few steps away from listing your property at Zipvilla.<br />
Tell us more about your place and complete your listing.</p></div>
    <div class="detials_form"><!--detials_form-->
        <form>
            <h2>Amenities</h2>
            <p>Check all the amenities available at your place</p>
            <div class="detials_form_l">
                <input type="checkbox" name="amenities" value="hotwater" />Hot Water<br />
                <input type="checkbox" name="amenities" value="parking" />Parking<br />
                <input type="checkbox" name="amenities" value="Kitchen" />Kitchen<br />
                <input type="checkbox" name="amenities" value="Television" />Television<br />
                <input type="checkbox" name="amenities" value="Air Conditioning" />Air Conditioning<br />
                <input type="checkbox" name="amenities" value="Washer Dryer" />Washer Dryer<br />
            </div>
            <div class="detials_form_r">
                <input type="checkbox" name="amenities" value="Cable or Satellite TV" />Cable or Satellite TV<br />
                <input type="checkbox" name="amenities" value="Gym" />Gym<br />
                <input type="checkbox" name="amenities" value="Internet" />Internet<br />
                <input type="checkbox" name="amenities" value="Wireless Internet" />Wireless Internet<br />
                <input type="checkbox" name="amenities" value="Swimming Pool" />Swimming Pool<br />
                <input type="checkbox" name="amenities" value="Parking" />Parking<br />
            </div>
            <div class="border"></div>
            <h2>Onsite services and suitability</h2>
            <p>Check all the services available to your guests at your place</p>
            <div class="detials_form_l">
                <input type="checkbox" name="onsiteservices" value="Cleaning" />Cleaning<br />
                <input type="checkbox" name="onsiteservices" value="Cook" />Cook<br />
                <input type="checkbox" name="onsiteservices" value="Laundry" />Laundry<br />
                <input type="checkbox" name="onsiteservices" value="Concierge" />Concierge<br />
            </div>
            <div class="detials_form_r">
                <input type="checkbox" name="onsiteservices" value="Pets Allowed" />Pets Allowed<br />
                <input type="checkbox" name="onsiteservices" value="Handicap Access" />Handicap Access<br />
            </div>
            <div class="border"></div>
            <h2>House rules</h2>
            <p>Mention the rules that guest must keep in mind during their stay at your place</p>
            <textarea cols="70" name="message" rows="5" class="FrmtxtArea"></textarea><br>
            <INPUT class="submit" type="submit" value="">
        </form>
    </div><!--detials_form ends here-->
</div><!--Property details ends here-->
<div class="l_property_right v_property_right">
    <div>
    <h4 class="l_link_back_page v_link_back_page"><a href="#">Back to Listings</a></h4>
    <h2>Need help? Call us:</h2>
    <p>+91-80-4115-0200<br />+91-80-4115-0400</p>
    </div>
    <div class="property_right_nav">
        <ul>
            <li><a href="<?php echo $this->baseUrl('/account/basicinfo');?>">Basic Information</a></li>
            <li><class="active1">Property Details</a></li>
            <li><a href="#">Calendar</a></li>
            <li style="border-bottom:none;"><a href="#">Photos and Videos</a></li>
        </ul>
    </div>
</div>

                                        