<?php $this->headTitle('User Registration'); ?>
<?php $this->layout()->setLayout('register_layout');?>
<?php
$firstname = '';
$lastname  = '';
$emailid   = '';
$password  = '';
$cnfrm_password = '';
if ($this->userdata) {
  $z = $this->userdata;
  $firstname = isset($z['firstname']) ? $z['firstname'] : '';  
  $lastname = isset($z['lastname']) ? $z['lastname'] : '';
  $emailid = isset($z['emailid']) ? $z['emailid'] : '';
  $password = isset($z['password']) ? $z['password'] : '';
  $cnfrm_password = isset($z['cnfrm_password']) ? $z['cnfrm_password'] : '';  
}
$errors = $this->form->getMessages();
$display_errors = array();
foreach($errors as $field => $error) {
    $display_errors[$field] = array();
    foreach($error as $k => $v) {
        $display_errors[$field][] = $v;
    }
}
function getError($errors, $name) {
    $html = '';
    if (isset($errors[$name])) {
        foreach($errors[$name] as $error) {
            $html .= '<p style="float:left;clear:both;color:red;">'.$error.'</p>';
        }
    }
    return $html;
}
?>
<div class="form-section">
   <form method="post" id="register" name="register" action="#">
    <label for="firstname">First name :<br /><?php echo getError($display_errors, 'firstname');?><input type="text" id="firstname" size="37" name="firstname" value="<?php echo $firstname;?>"/></label>
    <label for="lastname">Last name :<br /><?php echo getError($display_errors, 'lastname');?><input type="text" id="lastname" size="37" name="lastname" value="<?php echo $lastname;?>"/></label>
    <label for="emailid">Email address :<br /><?php echo getError($display_errors, 'emailid');?><input type="text" id="emailid" size="37" name="emailid" value="<?php echo $emailid;?>"/></label>
    <label for="password">Password :<br /><?php echo getError($display_errors, 'password');?><input type="password" id="password" size="37" name="password" value="<?php echo $password;?>"/></label>
    <label for="cnfrm_password">Confirm password :<br /><?php echo getError($display_errors, 'cnfrm_password');?><input type="password" id="cnfrm_password" size="37" name="cnfrm_password" value="<?php echo $cnfrm_password;?>"/></label>
    <div class="chk_bx"><input type="checkbox" id="accept_terms" name="accept_terms"/><p>I accept the <a href="#">Terms of Service</a></p><?php echo getError($display_errors, 'accept_terms');?></div>
    <input class="input" type="submit" id="login" name="login" value=""/>
   </form>
</div> <!-- / form-section -->