<?php
    include_once("ZipVilla/TypeConstants.php");
    //include_once("ZipVilla/Helper/php/index.php");
    //include_once("ZipVilla/Helper/php/upload.class.php");
    
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('Zipvilla ~ Home away from home in India');
    echo $this->doctype();
    $baseUrl = $this->baseUrl();
?>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink() 
                                    ->prependStylesheet('http://blueimp.github.com/cdn/css/bootstrap.min.css')
                                    ->prependStylesheet('http://blueimp.github.com/cdn/css/bootstrap-responsive.min.css')
                                    ->prependStylesheet('http://blueimp.github.com/Bootstrap-Image-Gallery/css/bootstrap-image-gallery.min.css')
                                    ->prependStylesheet($this->baseUrl().'../css/jquery.fileupload-ui.css')
                                    ->prependStylesheet($this->baseUrl().'/css/visual.css')
                                    ->prependStylesheet($this->baseUrl().'/css/layout.css')
                                    ->prependStylesheet($this->baseUrl().'/css/ui.theme.css')
                                    ->prependStylesheet($this->baseUrl().'/css/misc.css')
                                    ->prependStylesheet($this->baseUrl().'/css/ui-lightness/jquery-ui-1.8.16.custom.css')
                                    ->prependStylesheet($this->baseUrl().'/css/lightbox.css')
                                    ->prependStylesheet($this->baseUrl().'/css/jquery.ad-gallery.css')
                                    ; ?>

        <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery-min-164.js')
                                      ->appendFile('http://maps.googleapis.com/maps/api/js?sensor=false')
                                      ->appendFile('http://connect.facebook.net/en_US/all.js')
                                      ->appendFile($this->baseUrl().'/js/mapMarker.js')
                                      ->appendFile($this->baseUrl().'/js/accordian.js')
                                      ->appendFile($this->baseUrl().'/js/jquery-ui.min.js')
                                      ->appendFile($this->baseUrl().'/js/jquery.ad-gallery.js')
                                      ->appendFile($this->baseUrl().'/js/slideshow.js')
                                      ->appendFile($this->baseUrl().'/js/zvcommon.js')
                                       ;?>
                                       
        <?php $id = isset($this->listing) ? $this->listing->id : '';?>
        
        <script type="text/javascript">

        function showDialog(showtext, onaccept) 
        {
            var dialog = $('<div id="confirm" title="Please Confirm"></div>');
            dialog.html('<p>'+showtext+'</p>');
            dialog.dialog({
            	             autoOpen:false,
            	             buttons: {"Yes" : function() { $(this).dialog('close'); eval(onaccept);},
	                                   "No" : function() {$(this).dialog('close')}},
            	             modal:true,
            	             position:'center',
            	             dialogClass:'zvdialog'
            });
            dialog.dialog('open');
        }
            
        function setHover()
        {
            $('.info').hover(function() {
                                if ($(this).attr('title')) {
                                    $(this).data('message', $(this).attr('title'));
                                    $(this).removeAttr('title');
                                }
                                message = $(this).data('message');
                                $(this).attr('title', '');
                                $(this).append($("<div id='tooltip' class='tooltip'>"+message+"</div>"));
                             },
                             function() {
                            	$('#tooltip').remove();
                             });
        }

        function initPage()
        {
            setHover();
            $( ".checkin" ).datepicker({dateFormat:'dd-M-yy', minDate:0});
            $( ".checkout" ).datepicker({dateFormat:'dd-M-yy', minDate:0,
                                         beforeShowDay: enableCheckOutFor});
        }
            
        function getAccountData(_id, _type, _start, _filter)
        { 
        	$('#loadergif').show();
        	_filter = _filter || '';
        	$.ajax({ 
                type: "POST",
                url:"/default/account/getaccountdata/format/html",
                data:{type:_type, start:_start, filter:_filter},
                complete:function(data) {
        		             $('#loadergif').hide();
        		             $(_id).empty().html(data.responseText);
        		             initPage();
        		         }
	         });
        }
        function refreshBookings()
        {
        	var filter = $("#filter").val();
        	getAccountData('#tabs-1','bookings', 0, filter);
        }
        function deleteListing(_id, _listingId, _start, confirm)
        {
            confirm = confirm || 'yes';
            if (confirm == 'yes') { 
                var onaccept = 'deleteListing("'+_id+'","'+_listingId+'",'+_start+',"no")';
                showDialog('Do you really want to delete this listing?', onaccept);
                return;
            }
        	$('#loadergif').show();
        	$.ajax({ 
                type: "POST",
                url:"/default/account/deleteprelisting/format/html",
                data:{id:_listingId, start:_start},
                complete:function(data) {
                             $('#loadergif').hide();
                             $(_id).empty().html(data.responseText); 
                         }
             });
        }
        function activateListing(_id, _listingId, _start)
        {
            $('#loadergif').show();
            $.ajax({ 
                type: "POST",
                url:"/default/account/activatelisting/format/html",
                data:{id:_listingId, start:_start},
                complete:function(data) {
                             $('#loadergif').hide();
                             $(_id).empty().html(data.responseText); 
                         }
             });
        }
        function setBooking(_id, _leadId, _action, _start, _filter)
        {
        	$('#loadergif').show();
        	$.ajax({ 
                type: "POST",
                url:"/default/account/setbooking/format/html",
                data:{id:_leadId, action:_action, start:_start, filter:_filter},
                complete:function(data) {
                             $('#loadergif').hide();
                             $(_id).empty().html(data.responseText);
                             initPage();
                         }
             });
        	
        }

        function updateCalendar() 
        {
            var _available = $("input[name=available]:checked").val();
            var _from = $("input[name=from]").val();
            var _to = $("input[name=to]").val();
            var _price = $("input[name=price]").val();
            var _date = $(".dropdown_sm").val();
            var _id = "<?php echo $id;?>";
            
            if ((_from == '') || (_to == '') || (_price == '')) {
            	$('#lb_error').empty().prepend('<p> Incomplete input. Please complete all fields.</p>');
                return;
            }
            closelightbox('#lb_edit_calendar', '#mask_zv');
            $('#loadergif').show();
            $.ajax({ 
                type: "POST",
                dataType: "html",
                url:"/default/account/updatecalendar/format/html",
                data:{id:_id,from:_from, to:_to, available:_available, price:_price,date:_date},
                complete:function(data) { 
                    if (data.responseText.length > 10) { //ignore nil responses.
                        $('#loadergif').hide();
                        $('.calendar1').children('table').remove();
                        $(".calendar1").prepend(data.responseText);
                    }
                }
            });
        }
        
        $(document).ready(function() {
        	if ($('#tabs-1').length > 0) {
        		   $tabs = $('#tabs').tabs();
        		   getAccountData('#tabs-1','bookings', 0, 'A');
        		   getAccountData('#tabs-2','listings', 0);
        		   $tabs.tabs('select', <?php echo $this->showtab;?>);
        	}
        	$('.dropdown_sm').change(function() {
                var option = $(".dropdown_sm").val();
                $('#loadergif').show();
                $.ajax({ 
                    type: "POST",
                    dataType: "html",
                    url:"/default/account/getcalendar/format/html",
                    data:"date="+option+"&id="+'<?php echo $id;?>',
                    complete:function(data) {
                         $('#loadergif').hide();
                         $('.calendar1').children('table').remove();
                         $(".calendar1").prepend(data.responseText);
                    }
                });
            });
        	if ($('.dropdown_sm').length > 0) {
        		   $('.dropdown_sm').prop('selectedIndex', "<?php echo date('M  Y');?>");
        		   $.ajax({ 
        			    type: "POST",
        			    dataType: "html",
        			    url:"/default/account/getcalendar/format/html",
        			    data:"date="+"<?php echo date('M  Y');?>"+"&id="+'<?php echo $id;?>',
        			    complete:function(data) { 
                            $(".calendar1").prepend(data.responseText);
                        }
        		    });
        	}
        	$('#calendar1').click(function() {
        		showlightbox('#lb_edit_calendar', '#mask_zv');
        	});
        });
        
      	</script>
</head>

<body class="blue">
    <div id="fb-root"></div>
	<div class="wrapper"><!--outer wrapper to fix the width-->
        <?php echo $this->render('header.phtml');?>
        <div class="content">
            <?php echo $this->layout()->content; ?>
        </div><!-- content ends here -->
        <?php echo $this->render('footer.phtml');?>
    </div><!-- wrapper ends here -->
</body>
</html>

