<?php
    include_once("ZipVilla/TypeConstants.php");
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('Zipvilla-Feel at Home-Away');
    echo $this->doctype();
    $baseUrl = $this->baseUrl();
?>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/visual.css')
                                    ->prependStylesheet($this->baseUrl().'/css/layout.css')
                                    ->prependStylesheet($this->baseUrl().'/css/ui.theme.css')
                                    ->prependStylesheet($this->baseUrl().'/css/ui-lightness/jquery-ui-1.8.16.custom.css')
                                    ->prependStylesheet($this->baseUrl().'/css/lightbox.css')
                                    ->prependStylesheet($this->baseUrl().'/css/misc.css')
                                    ->prependStylesheet($this->baseUrl().'/css/jquery.ad-gallery.css')
                                    ; ?>

        <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery-min-164.js')
                                      ->appendFile('http://maps.googleapis.com/maps/api/js?sensor=false')
                                      ->appendFile($this->baseUrl().'/js/mapMarker.js')
                                      ->appendFile($this->baseUrl().'/js/zvcommon.js')
                                      ->appendFile($this->baseUrl().'/js/accordian.js')
                                      ->appendFile($this->baseUrl().'/js/jquery-ui.min.js')
                                      ->appendFile($this->baseUrl().'/js/jquery.ad-gallery.js')
                                      ->appendFile($this->baseUrl().'/js/slideshow.js')
                                      ->appendFile($this->baseUrl().'/js/facebook.js')
                                       ;?>
        
        <script type="text/javascript">
        	        
        $(document).ready(function(){
            mapMarker('map', 1);
            $("#show_rate_options").change(function() {
                var option = $("#show_rate_options").val();
                $("#show_rate").text("Rs. "+option);
            });
            $('.dropdown_sm').change(function() {
            	var option = $(".dropdown_sm").val();
            	$('#loadergif').empty().html("<img src=\"<?php echo $this->baseUrl('/css/loader.gif');?>\"/>");
            	$.ajax({ 
                    type: "POST",
                    dataType: "html",
                    url:"/default/list/getcalendar/format/html",
                    data:"id="+'<?php echo $this->property->id;?>'+"&date="+option,
                    complete:function(data) {
                    	 $('#loadergif').empty();
            	         $('.calendar1').children('table').remove();
                         $(".calendar1").prepend(data.responseText);
                    }
                });
            });
            $('.dropdown_sm').prop('selectedIndex', "<?php echo date('M  Y');?>");
            $.ajax({ 
                type: "POST",
                dataType: "html",
                url:"/default/list/getcalendar/format/html",
                data:"id="+'<?php echo $this->property->id;?>'+"&date="+'<?php echo date('M  Y');?>',
                complete:function(data) { 
                     //$('.calendar1').children('table').remove();
                     $(".calendar1").prepend(data.responseText);
                }
            });
            calculate_rate();
            $(".defaultText").focus(function(srcc) {
               if ($(this).val() == $(this)[0].title) {
                   $(this).removeClass("defaultTextActive");
                   $(this).val("");
               }
            });
                   
            $(".defaultText").blur(function() {
               if ($(this).val() == "") {
                   $(this).addClass("defaultTextActive");
                   $(this).val($(this)[0].title);
               }
            });
                   
            $(".defaultText").blur();

            <?php if ($this->property != null) {?>
            getReviews(0);
            <?php }?>

            <?php if ($this->showPopupMsg) {?>
            showlightbox('#lb_thankyou', '#maskzv', '<?php echo $this->showPopupMsg;?>');
            <?php } ?>
        });

        function validate(id, names) 
        {
            var isvalid = true;
            $(names).each(function(i) {
                var input = $(id+" :input[name=\""+names[i]+"\"]");
                if (input != null) {
                    var classname = input.attr('class');
                    if (classname.match(/defaultText/)) {
                        if (input.val() == input[0].title) {  
                            input.val('');
                        }
                    }
                    if (input.val() == '') { 
                       isvalid=false;
                       
                    }
                }
                else {
                    isvalid= false;
                }
            });
            return isvalid;
        }

        function getReviews(_start) {
            var _baseurl = '<?php echo $this->baseUrl();?>'; 
            var _id = '<?php echo $this->property->id;?>';
            $.ajax({ 
                type: "POST",
                dataType: "json",
                url:"/default/list/getreviews/format/json",
                data:{id:_id, start:_start, baseurl:_baseurl},
                complete:function(json) { 
                	var resp = jQuery.parseJSON(json.responseText.substring(2)); 
                	$("#user_reviews").html(resp.user_reviews);
                	$("#user_reviews_notice").html(resp.user_reviews_notice);
                	$("#user_reviews_pages").html(resp.user_reviews_pages);
                }
            });
        }
        
      	
      	</script>
</head>

<body class="blue">
    <div id="fb-root"></div>
	<div class="wrapper"><!--outer wrapper to fix the width-->
        <?php echo $this->render('header.phtml');?>
        <div class="content">
            <?php echo $this->layout()->content; ?>
        </div><!-- content ends here -->
        <?php echo $this->render('footer.phtml');?>
    </div><!-- wrapper ends here -->
</body>
</html>

