<?php
    include_once("ZipVilla/TypeConstants.php");
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('Zipvilla-Feel at Home-Away');
    echo $this->doctype();
    $baseUrl = $this->baseUrl();
?>
<html>
<head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/visual.css')
                                    ->prependStylesheet($this->baseUrl().'/css/layout.css')
                                    ->prependStylesheet($this->baseUrl().'/css/ui.theme.css')
                                    ->prependStylesheet($this->baseUrl().'/css/ui-lightness/jquery-ui-1.8.16.custom.css')
                                    ->prependStylesheet($this->baseUrl().'/css/lightbox.css')
                                    ->prependStylesheet($this->baseUrl().'/css/misc.css')
                                    ->prependStylesheet($this->baseUrl().'/css/jquery.ad-gallery.css')
                                    ; ?>

        <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery-min-164.js')
                                      ->appendFile('http://maps.googleapis.com/maps/api/js?sensor=false')
                                      ->appendFile($this->baseUrl().'/js/mapMarker.js')
                                      ->appendFile($this->baseUrl().'/js/zvcommon.js')
                                      ->appendFile($this->baseUrl().'/js/accordian.js')
                                      ->appendFile($this->baseUrl().'/js/jquery-ui.min.js')
                                      ->appendFile($this->baseUrl().'/js/jquery.ad-gallery.js')
                                      ->appendFile($this->baseUrl().'/js/slideshow.js')
                                       ;?>
        
        <script type="text/javascript">
        	        
        $(document).ready(function(){
            mapMarker('map', 1);
            $("#show_rate_options").change(function() {
                var option = $("#show_rate_options").val();
                $("#show_rate").text("Rs. "+option);
            });
           calculate_rate();
           $(".defaultText").focus(function(srcc) {
               if ($(this).val() == $(this)[0].title) {
                   $(this).removeClass("defaultTextActive");
                   $(this).val("");
               }
            });
                   
           $(".defaultText").blur(function() {
               if ($(this).val() == "") {
                   $(this).addClass("defaultTextActive");
                   $(this).val($(this)[0].title);
               }
            });
                   
           $(".defaultText").blur();

           <?php if ($this->property != null) {?>
           getReviews(0);
           <?php }?>
        });

        function validate() 
        {
            var isvalid = false;
            $(".defaultText").each(function(i) {
                if ($(this).val() == $(this)[0].title) 
                    $(this).val(''); 
                else 
                    isvalid=true;
                }
            );
            if (!isvalid) 
            	$(".defaultText").blur();
            return isvalid;
        }

        function getReviews(_start) {
            var _baseurl = '<?php echo $this->baseUrl();?>'; 
            var _id = '<?php echo $this->property->id;?>';
            $.ajax({ 
                type: "POST",
                dataType: "json",
                url:"/default/list/getreviews/format/json",
                data:{id:_id, start:_start, baseurl:_baseurl},
                complete:function(json) { 
                	var resp = jQuery.parseJSON(json.responseText.substring(2)); 
                	$("#user_reviews").html(resp.user_reviews);
                	$("#user_reviews_notice").html(resp.user_reviews_notice);
                	$("#user_reviews_pages").html(resp.user_reviews_pages);
                }
            });
        }
        
      	
      	</script>
</head>
    
<body class="blue">
	<div class="wrapper"><!--outer wrapper to fix the width-->
        <?php echo $this->render('header.phtml');?>
        <div class="content">
            <?php echo $this->layout()->content; ?>
        </div><!-- content ends here -->
        <?php echo $this->render('footer.phtml');?>
    </div><!-- wrapper ends here -->
</body>
</html>

