<div class="footer">
    <div class="dsclimr"><p><span>&copy; 2011  ZipVilla.  All rights reserved.</span><a href="#">Privacy Policy</a>|<a href="#">Terms and Conditions</a></p></div>
    <div class="l_futr_nav v_futr_nav">
        <ul>
            <li><a href="#">How it works</a></li>
            <li><a href="#">FAQs</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Jobs</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
    </div>
    <div class="social_ico">
        <ul>
            <li><a href="#"><img src="images/icon_fb.jpg" alt="Facebook"></a></li>
            <li><a href="#"><img src="images/icon_twitter.jpg" alt="twitter"></a></li>
        </ul>
    </div>
</div><!--footer ends here-->
