<div class="header"><!--header section-->
	<div class="logo"><a href="<?php echo $this->baseUrl('/');?>"><img src="<?php echo $this->baseUrl('/images/logo_zipvilla.jpg');?>" alt="Zipvilla" /></a></div>
    <div class="v_top_nav l_top_nav">
    	<ul>
    	    <li><a href="<?php echo $this->url(array('controller' => 'search', 'action' => 'reindex'));?>">Index</a></li>
        	<li><a href="#">How Zipvilla Works</a></li>
            <li id="logged_in_as"><?php echo $this->loggedInAs(); ?></li>
            <li class="last"><?php echo $this->registerLink(); ?></li>
        </ul>
    </div><!--top_nav ends-->
</div><!--header ends here-->
