<?php /* echo $this->layout()->content; */ ?>
<?php
    include_once("ZipVilla/TypeConstants.php");
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('Zipvilla ~ Feel at Home-Away.');
    echo $this->doctype();
    $baseUrl = $this->baseUrl();
    $this->addScriptPath(APPLICATION_PATH.'/views/scripts/index'); 
    $url = $this->url(array('controller'=>'search',
                            'action' => 'index', 
                            'query'=> $this->search_query,
                            'check_in' => $this->checkin,
                            'check_out' => $this->checkout,
                            'guests' => $this->guests), null, TRUE);
?>
<html>
<head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/skins/ie7/skin.css')
                                    ->prependStylesheet($this->baseUrl().'/skins/tango/skin.css')
                                    ->prependStylesheet($this->baseUrl().'/css/galleriffic-2.css')
                                    ->prependStylesheet($this->baseUrl().'/css/jquery.ad-gallery.css')
                                    ->prependStylesheet($this->baseUrl().'/css/lightbox.css')
                                    ->prependStylesheet($this->baseUrl().'/css/ui-lightness/jquery-ui-1.8.16.custom.css')
                                    //->prependStylesheet($this->baseUrl().'/css/ui.theme.css')
                                    ->prependStylesheet($this->baseUrl().'/css/layout.css')
                                    ->prependStylesheet($this->baseUrl().'/css/visual.css')

                                    ->prependStylesheet($this->baseUrl().'/css/misc.css')
                                    ; ?>

        <?php echo $this->headScript()
                                      ->appendFile($this->baseUrl().'/js/jquery-1.6.2.min.js')
                                      ->appendFile($this->baseUrl().'/js/jquery-ui-1.8.16.custom.min.js')
                                      ->appendFile($this->baseUrl().'/js/accordian.js')
                                      //->appendFile('http://maps.googleapis.com/maps/api/js?sensor=false')
                                      ->appendFile($this->baseUrl().'/js/mapMarker.js')
                                      ->appendFile($this->baseUrl().'/js/zvcommon.js')
                                      ->appendFile($this->baseUrl().'/js/jquery.galleriffic.js')
                                      ->appendFile($this->baseUrl().'/js/jquery.opacityrollover.js')
                                      ->appendFile($this->baseUrl().'/js/galleriffic.js')
                                      ->appendFile($this->baseUrl().'/js/jquery.jcarousel.min.js')
                                      ->appendFile($this->baseUrl().'/js/jquery.ad-gallery.js')
                                      ->appendFile($this->baseUrl().'/js/slideshow.js')
        
                                       ;?>
<script type="text/javascript">
document.write('<style>.noscript { display: none; }</style>');
</script> 
                                      
<script type="text/javascript">

function watchQueryBox() {
    if ($('#query').data('lastValue') != $('#query').val()) {
        $.ajax({ 
            type: "POST",
            url:"/default/search/lookahead/format/html",
            data:"query="+$('#query').val(),
            complete:function(data) { console.log(data.responseText);}});
        $('#query').data('lastValue', $('#query').val());
    }
}

$(document).ready(function() {
    // Initialise the first and second carousel by class selector.
    // Note that they use both the same configuration options (none in this case).
    $('.first-and-second-carousel').jcarousel({wrap:"circular"});
    
    $("#guests").val('1');

    $('#query').data('lastValue', '<?php //echo $this->search_query;?>');
    $('#query').bind('keypress', null, watchQueryBox);

    $(".defaultText").focus(function(srcc) {
        if ($(this).val() == $(this)[0].title) {
            $(this).removeClass("defaultTextActive");
            $(this).val("");
        }
     });
        
    $(".defaultText").blur(function() {
        if ($(this).val() == "") {
            $(this).addClass("defaultTextActive");
            $(this).val($(this)[0].title);
        }
     });
        
    $(".defaultText").blur(); 
});

$(function() {
    $( "#checkin" ).datepicker();
});
$(function() {
    $( "#checkout" ).datepicker();
});

    
</script>
                                       
        <?php //echo $this->render('search_page_js.phtml'); ?>

</head>
<body class="blue">
	<div class="wrapper"><!--outer wrapper to fix the width-->
		<?php echo $this->render('header.phtml');?>
		<div class="content">
			<div class="srch_bx_home"><!--srch_bx_home-->
				<h1>Discover amazing places to stay.</h1>
				<p>1000s of exclusive properties in over a 100 cities awaiting your arrival.</p>

				<div class="home_search"><!--home search-->
					<form id="search_form_home" name="search_form_home" action="/search" method="post">
						<?php echo $this->render('home_search.phtml');?>
					</form>
				</div><!--home search ends-->
			</div><!--srch_bx_home ends-->

			<div class="slide_right"><!--slideshow-right-->
				<?php echo $this->render('home_sponsored.phtml');?>
			</div><!--slideshow-right ends-->
			<div class="bg_slide_btm"></div>

			<div class="slide_bottom">
				<?php echo $this->render('home_slide_bottom.phtml');?>
			</div>
		</div> <!--content ends here-->
			<?php echo $this->render('footer.phtml');?>
	</div><!--wrapper ends here-->
</body>

</html>

