<?php /* echo $this->layout()->content; */ ?>
<?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('ZipVilla');
    echo $this->doctype(); 
?>
<html>
<head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
        <?php echo $this->headScript()->appendFile('/js/jquery-min-164.js') 
                                      ->appendFile('/js/mapMarker.js')
                                      ->appendFile('http://maps.googleapis.com/maps/api/js?sensor=false');?>
        <script type="text/javascript">
        function doSearch(id) {
            var city = document.getElementById(id).value;
            window.location.href = '/search?city='+city;
        } 
        </script>
</head>
    
    <body>
      <div id="zvContainer">
        <div id="zvHeader">
          <img src = "/images/zipvilla_logo.jpg" alt="ZipVilla header"></img>
        </div>
    	<div id="header"> 
    		<div id="logged-in-as">
				<?php echo $this->loggedInAs(); ?> 
			</div>
		</div>
		<div id="header2"> 
    		<div id="register-link">
				<?php echo $this->registerLink(); ?> 
			</div>
		</div>
		<div id="whereTo">
			<p>
				<input type="text" name="city_id" id="city_id" size="50"
					maxlength="50" />
			</p>
		</div>
		<div id="colSearch">
			<div id="colSearchIcon">
				<p>
					<img src="/images/search_world_icon.jpg" width="45" height="35"
						alt="image 1" />
				</p>
			</div>
			<div id="colSearchText">
				<p>
					<input type="button" value="Search" onclick="doSearch('city_id');"/>
				</p>
			</div>
			<div id="colIndexText">
                <p>
                    <input type="button" value="Re-Index" onclick="window.location.href='/search/reindex';"/>
                </p>
            </div>
		</div>
		<div id="content">
            	<h1><?php echo $this->escape($this->title); ?></h1>
            	<?php echo $this->layout()->content; ?>
        	</div>
        	<div id="zvMapInfo">
        	   MapVilla
        	</div>
        <div id="zvFooter">
        	<img src="/images/zipvilla_footer.jpg" alt="ZipVilla footer"></img>
        </div>
      </div>
    </body>
</html>
