<?php /* echo $this->layout()->content; */ ?>
<?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('Zipvilla-Feel at Home-Away');
    echo $this->doctype();
    $baseUrl = $this->baseUrl();
?>
<html>
<head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/visual.css')
                                    ->prependStylesheet($this->baseUrl().'/css/layout.css')
                                    ->prependStylesheet($this->baseUrl().'/css/ui-lightness/jquery-ui-1.8.16.custom.css'); ?>
        
        <?php echo $this->headScript()->appendFile('http://connect.facebook.net/en_US/all.js')
                                      ->appendFile($this->baseUrl().'/js/jquery-min-164.js') 
                                      ->appendFile($this->baseUrl().'/js/jquery-ui-1.8.16.custom.min.js')
                                      ->appendFile($this->baseUrl().'/js/accordian.js')
                                      ->appendFile($this->baseUrl().'/js/zvcommon.js')
                                      ;?>

</head>
<body class="blue">
    <div id="fb-root"></div>
    <div class="wrapper"><!--outer wrapper to fix the width-->
        <?php echo $this->render('header.phtml');?>
        <div class="content"><!--content starts here-->
            <div class="v_rgstr_frm l_rgstr_frm">
                <h1>Join Zipvilla.</h1>
                <div class="register"><!--left side content-->
                    <?php echo $this->layout()->content; ?>
                </div><!--left side content ends-->
                <div class="v_ctnt_right_regst"><!--right side content-->
                    <div><img src="<?php echo $baseUrl?>/images/btn_connect_fb.jpg" alt="facebook"></div>
                    <p>Already a member of Zipvilla?<br><span><a href="#">Login now.</a></span></p>
                </div><!--right side content ends-->
            </div><!--registration form ends here-->
        </div><!--content ends here-->
        <?php echo $this->render('footer.phtml');?>
    </div><!--wrapper ends here-->
</body>
</html>

