<?php 
    $ctr = 1+($this->page - 1) * $this->pagesz;

    $low = MIN_RATE; $high = MAX_RATE;
    if (isset($this->price_range)) {
        $low=$this->price_range[0];
        $high=$this->price_range[1];
    }
    $sort = 0;
    if (isset($this->sortorder)) {
        if ($this->sortorder == 'hl') {
            $sort = 1;
        }
        elseif ($this->sortorder == 'lh') {
            $sort = 2;
        }
    }
?>

<script type="text/javascript">

    var $tabs;
    	        
    $(document).ready(function(){
    	   
        //mapMarker('map', <?php echo $ctr;?>);
        mapMarker('map', 1);
        
    	$( "#price_range" ).val( "Rs." + $( "#price_slider" ).slider( "values", 0) +
                " - Rs." + $( "#price_slider" ).slider( "values", 1 ));
    
    	$("#guests").val("<?php echo $this->guests;?>");
    	<?php if ((isset($this->search_query)) &&  ($this->search_query != '*')){?>
    	   $("#query").val("<?php echo $this->search_query;?>");
    	<?php }?>
    	
    	$("#sort").prop('selectedIndex', <?php echo $sort;?>);
    	$('#query').data('lastValue', '<?php echo $this->search_query;?>');
    	$('#query').autocomplete({source:'/default/search/autocomplete/format/json'});
    
        $('#price_slider').slider({
            range: true,
            min: 100,
            max:20000,
            values: [minPrice, maxPrice],
            step:100,
            change: function( event, ui ) {
                $( "#price_range" ).val( "Rs." + ui.values[ 0 ] + " - Rs." + ui.values[ 1 ] );
                refineSearch('price_range', ui.values[0]+'-'+ui.values[1], 'false');
            }
        });
        $('#price_slider').slider({
            values: [<?php echo $low;?>, <?php echo $high;?>],
        });
        $( "#price_range" ).val( "Rs." + $( "#price_slider" ).slider( "values", 0 ) +
                " - Rs." + $( "#price_slider" ).slider( "values", 1 ) );

        $tabs = $('#tabs').tabs();
        $tabs.tabs('select', <?php echo $this->showtab;?>);
 				$('#tabs').bind('tabsshow', function(event, ui) {
 			    if (ui.panel.id == "tabs-3") {
  	 				mapMarker('tab_search_map_div', 1,15,1);  	 			    }
	 			});

 		$('input[name$="[]"]').change(function() {
 	 		var facet = $(this).attr('name').replace("[]", "");
 	 		var checked = 'true';
 	 		if (typeof $(this).attr('checked') == 'undefined')
 	 	 		checked = 'false';
	 	 	var value = $(this).val();
	 	 	refineSearch(facet, value, checked);
	 	  });

 		$('#keywords').keypress(function(e) {
 		    var code= (e.keyCode ? e.keyCode : e.which);
 		    if ((code == 13) || (code == 10)) {
 		    	refineSearch('keywords', $(this).val(), false);
 		    	e.preventDefault();
 		    }
 		 });
 		 		  
    });

</script>
