<?php /* echo $this->layout()->content; */ ?>
<?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('Zipvilla-Feel at Home-Away');
    echo $this->doctype();
    $baseUrl = $this->baseUrl();
?>
<html>
<head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/visual.css')
                                    ->prependStylesheet($this->baseUrl().'/css/layout.css')
                                    ->prependStylesheet($this->baseUrl().'/css/ui-lightness/jquery-ui-1.8.16.custom.css'); ?>
        
        <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery-min-164.js') 
                                      ->appendFile($this->baseUrl().'/js/jquery-ui-1.8.16.custom.min.js')
                                      ->appendFile($this->baseUrl().'/js/accordian.js');?>

</head>
<body class="blue">
    <div class="wrapper"><!--outer wrapper to fix the width-->
        <?php echo $this->render('header.phtml');?>
        <div class="content"><!--content starts here-->
        <div class="v_rgstr_frm l_rgstr_frm">
            <h1><?php echo $this->headline;?></h1>
            <?php echo $this->layout()->content; ?>
            <div class="v_ctnt_right_regst"><!--right side content-->
            </div><!--right side content ends-->
        </div><!--registration form ends here-->
        </div><!--content ends here-->
        <?php echo $this->render('footer.phtml');?>
    </div><!--wrapper ends here-->
</body>

</html>

