<?php
include_once "ZipVilla/TypeConstants.php";
$this->title = "Property Detail";
$this->headTitle($this->title);
$this->layout()->setLayout('detail');
$property = $this->property;
$baseUrl = $this->baseUrl();
$logger = Zend_Registry::get('zvlogger');
if ((!isset($this->user_rating)) || ($this->user_rating == null)) {
    $this->user_rating = 0;
}
$this->addScriptPath(APPLICATION_PATH.'/views/scripts/list');
//$mapHelper = $this->map();
?>

<?php if ($property == null) {?>
    <p>There has been an internal error. The property is not found in the system.</p>
<?php } else {?> <!-- Property detail available -->
<?php $country = isset($property->address['country']) ? $property->address['country'] : 'India';
      $address = $property->{'address.street_number'} . ', ' . $property->{'address.street_name'} . ', ' .
                 $property->{'address.location'} . ', '. $property->{'address.city'} . ', '. $property->{'address.state'} .', '.
                 $country;
      $property_type = $property->shared == 'yes' ? 'Shared house/villa' : 'Entire house/villa';
      $daily_rate = isset($property->rate['daily']) ? $property->rate['daily'] : 0;
      $weekly_rate = isset($property->rate['weekly']) ? $property->rate['weekly'] : 0;
      $monthly_rate = isset($property->rate['monthly']) ? $property->rate['monthly'] : 0;
      if ($weekly_rate == 0) $weekly_rate = 7 * $daily_rate;
      if ($monthly_rate == 0) $monthly_rate = 30 * $daily_rate;
      $room_type = "Entire home/villa";
      if ($property->shared == 'yes') $room_type = "Shared home/villa";
      $owner = $property->getOwner();
      $owner_name = '';
      $owner_image = 'default_user_image.jpg';
      if ($owner != null) {
          $owner_name = $owner->firstname . ' ' . $owner->lastname;
          $owner_image = $owner->image;
      }
      $reviews = Application_Model_Reviews::count(array('listing' => $property->getRef()));
      $zvId = $property->{ZIPVILLA_ID};
      
?>
<div class="v_social_ico l_social_ico">
                <h4 class="l_link_back_page v_link_back_page"><a href="/search">Back to search results</a></h4>
                <div class="l_social_netwrk"><img src="<?php echo $this->baseUrl('/images/icon_so_netwrk.jpg');?>" /></div>
            </div>
            <div class="v_listing_header">
                <div class="h2"><h1><?php echo $this->escape($property->title);?></h1><span><a href="#"></a></span>
                    <h2><?php echo $address;?></h2>
                    <div class="entire_villa"><p><?php echo $property_type;?></p></div>
                    <div class="entire_villa"><p><?php echo $zvId;?></p></div>
                </div>
                <div class="v_ratings">
                    <div class="ratings"><!--golden and silver stars-->
                        <ul>
                           <?php for($rc=0; $rc < MAX_RATING; $rc++) {
                                if ((0+$property->rating) > $rc) 
                                    echo '<li><img src="'.$this->baseUrl('/images/icon_ratings_gold.jpg').'"/></li>';
                                else
                                    echo '<li><img src="'.$this->baseUrl('/images/icon_ratings_silver.jpg').'"/></li>';
                                } 
                           ?>
                        </ul>
                        <span>Av. Rating <?php echo $property->rating?></span>
                    </div>
                    <div class="reviews">
                        <p><?php echo $reviews;?></p>
                        <span>Reviews</span>
                    </div>
                </div>
            </div><!--v_listing_header ends here-->
            <div class="l_search_results v_search_results"><!--Search result sections starts here-->
                <div id="tabs"><!--tabs-->
                    <ul>
                        <li><a href="#tabs-1">Photos</a></li>
                        <li><a href="#tabs-2">Videos</a></li>
                        <li><a href="#tabs-3">Map</a></li>
                        <li><a href="#tabs-4">Availability</a></li>
                    </ul>
                    <!-- <div class="ui-tabs-panel ui-widget-content ui-corner-bottom">  -->
                        <div id="tabs-1">
                            <div class="tab_content">
                                <?php echo $this->render('tab_photos.phtml');?>
                            </div>
                        </div>
                        <div id="tabs-2">
                            <div class="tab_content">
                                <?php echo $this->render('tab_videos.phtml');?>
                            </div>
                        </div>
                        <div id="tabs-3">
                            <div class="tab_content">
                                <?php echo $this->render('tab_photo_map.phtml');?>
                            </div>
                        </div>
                        <div id="tabs-4">
                            <div class="tab_content">
                                <?php echo $this->render('tab_availability.phtml');?>
                            </div>
                        </div>
                        <div class="ui-tabs-panel ui-widget-content ui-corner-bottom">
                    <div class="tab_content">
                        <div class="l_about_villa_left">
                            <h2>About your stay</h2>
                            <p><?php echo $property->description;?></p>
                        </div><!--l_about_villa_left ends-->
                        <div class="l_about_villa_right">
                            <h2>Amenities</h2>
                            <div class="amnts">
                                <ul>
                                    <?php 
                                         $features = array('amenities', 'onsite_services', 'suitability');
                                         foreach($features as $feature) {
                                            if ($property->{$feature} != null) {
                                                foreach($property->{$feature} as $k => $v) { 
                                                    $icon = preg_replace('/ /','', $k); ?>
                                                    <li><img src="<?php echo $this->baseUrl('/images/ico_swm.jpg');?>" title="<?php echo $k;?>"/></li>
                                          <?php } 
                                            }
                                         } 
                                    ?>
                                </ul>
                            </div>
                            <h2>House Rules</h2>
                            <p><?php echo $property->house_rules;?></p>
                        </div><!--l_about_villa_right ends-->
                        <div class="ratng_rvews">
                            <h2>Ratings &amp; Reviews</h2>
                            <div class="ratings"><!--golden and silver stars-->
                                <span>Average rating</span>
                                <ul>
                                    <?php for($rc=0; $rc < MAX_RATING; $rc++) {
                                        if ((0+$property->rating) > $rc) 
                                            echo '<li><img src="'.$this->baseUrl('/images/icon_ratings_gold.jpg').'"/></li>';
                                        else
                                            echo '<li><img src="'.$this->baseUrl('/images/icon_ratings_silver.jpg').'"/></li>';
                                        } 
                                    ?>
                                    <!-- <li><?php echo $property->rating;?></li> -->
                                </ul>
                                <span>Based on <?php echo $reviews;?> reviews</span>
                            </div>
                            <div class="ratings"><!--golden and silver stars-->
                                <span>Have you been here?</span>
                                <ul>
                                    <?php for($rc=0; $rc < MAX_RATING; $rc++) {
                                        $score = $rc+1;
                                        $url = $this->baseUrl('list/rate?id='.$property->id);
                                        //echo '<a href="'.$url.'&score='.$score.'">';
                                        echo '<a onclick="setRate('.$score.','.MAX_RATING.",'".$this->baseUrl(). "'" .');return false;">';
                                        if ((0+$this->user_rating) > $rc)
                                            echo '<li><img id="rate'.$score.'" src="'.$this->baseUrl('/images/icon_ratings_gold.jpg').'"/></li>';
                                        else 
                                            echo '<li><img id="rate'.$score.'" src="'.$this->baseUrl('/images/icon_ratings_silver.jpg').'"/></li>';
                                        echo '</a>';
                                    }?>                                
                                </ul>
                                <span>Rate your experience</span>
                            </div>
                            <div class="write_review">
                                <p><strong><?php echo $reviews;?> Reviews</strong></p>
                                <div class="btn_write_review"><a href="#" onclick="writeReview('.form_write_review');return false;"><img src="<?php echo $this->baseUrl('/images/btn_writ_revew.jpg');?>" alt="Write review"></a></div>
                            </div><!--write_review ends-->
                        </div><!--ratng_rvews ends-->
                        <div id="user_reviews">
                        </div>
                        <div id="div_review_form" class="form_write_review" style="display:none;">
                            <FORM id="review_form" action="#" method="post">
                                <textarea name="title" title="Your title for the review" style="width:100%;" cols="100" name="message" rows="1" class="FrmtxtArea defaultText"></textarea><br>
                                <textarea name="content" title="Share your experience..." style="width:100%;" cols="100" name="message" rows="3" class="FrmtxtArea defaultText"></textarea><br>
                                <input type="hidden" name="id" value="<?php echo $property->id;?>" />
                                <input type="hidden" name="rating" value="<?php echo $this->user_rating;?>" />
                                <div align="center"><INPUT type="submit" value="Submit review" onclick="submitForm('#review_form', ['title', 'content'], '#div_review_form'); return false;"> </div>
                            </FORM>
                        </div>
                    </div><!--tab_content ends here-->
                   
                    <div id="user_reviews_notice">
                    </div> 
                    <div id="user_reviews_pages">
                    </div>
                     </div>
                        <!-- 
                        <div class="l_page_buttons">
                            <div class="btn_prev_page"><a href="#"><img src="images/btn_prev_page.jpg" alt="Previous page" /></a></div>
                            <div class="btn_next_page"><a href="#"><img src="images/btn_next.jpg" alt="Next page" /></a></div>
                        </div> -->
                </div>
            </div><!--search result ends here-->
            <div class="l_right_side_panel v_right_side_panel">
                <div>
                    <h3>Make an online reservation</h3>
                </div>
                <div class="online_resrv">
                    <div>
                        <p>From</p>
                        <h2 id="show_rate">Rs. <?php echo $daily_rate;?></h2>
                    </div>
                    <div class="online_resrv_dropdwn">
                        <form action="">
                            <select id="show_rate_options" name="per night">
                                <option selected="selected" value="<?php echo $daily_rate;?>">per night</option>
                                <option value="<?php echo $weekly_rate;?>">per week</option>
                                <option value="<?php echo $monthly_rate;?>">per month</option>
                            </select>
                        </form>
                    </div>
                    <div class="form_online">
                        <form id="pre_send_details" action="" method="get">
                            <div class="floatleft"><label for="checkin">Check in<br /><input class="l_input_bg v_input_bg defaultText checkin" title="<?php echo DATE_FORMAT;?>" type="text" size="8" name="check_in" value="<?php echo $this->checkin;?>"/></label></div>
                            <div class="floatleft"><label for="checkout">Check out<br /><input class="l_input_bg v_input_bg defaultText checkout" title="<?php echo DATE_FORMAT;?>" type="text" size="8" name="check_out" value="<?php echo $this->checkout;?>"/></label></div>
                            <div class="floatleft">
                                <label for="guests" style="margin-right:1px;">Guests<br /><input type="text" class="v_dropdwon_bg l_dropdwon_bg" id="guests" name="guests" value="<?php echo $this->guests;?>"/>
                                </label>
                            </div>
                        </form>
                    </div>
                    <div class="sub_total">
                        <!-- <button type="button" onclick="calculate_rate('<?php echo $property->id;?>');">Calculate</button>  -->
                        <!-- <p>Subtotal</p> -->
                        <h2 id="calc_rate"></h2>
                        <span>(excludes any applicable taxes.)</span>
                        <div class="btn_send_details"><a href="#" onclick="showSendForm('#pre_send_details', '#send_details');return false;"><img src="<?php echo $this->baseUrl('/images/btn_send_details.jpg');?>" /></a></div>
                    </div>
                </div>
                <div class="l_refine_results v_refine_results">
                    <div class="l_price">
                        <div class="l_accordian_open"><a href="#"><img src="<?php $this->baseUrl('/images/btn_acco_open.jpg');?>" /></a></div>
                        <h4><a href="#">Accomodation Details</a></h4>
                        
                        <div class="acco_dtls">
                            <p>Room type:<span><?php echo $room_type; ?></span></p>
                        </div>
                        <div class="acco_dtls">
                            <p>Bed Type:<span> ? </span></p>
                        </div>
                        <div class="acco_dtls">
                            <p>Accomodates:<span><?php echo $property->guests; ?></span></p>
                        </div>
                        <div class="acco_dtls">
                            <p>Bedrooms:<span><?php echo $property->bedrooms; ?></span></p>
                        </div>
                        <div class="acco_dtls">
                            <p>Baths:<span><?php echo $property->baths; ?></span></p>
                        </div>
                        <div class="acco_dtls">
                            <p>Country:<span class="blue"><?php echo $country; ?></span></p>
                        </div>
                    </div>
                    <div class="l_price">
                    
<!--                    <div class="l_accordian_open"><a href="#"><img src="<?php echo $this->baseUrl('/images/btn_acco_open.jpg');?>" /></a></div>  -->
                        <div class="l_accordian_open"><img src="<?php echo $this->baseUrl('/images/btn_acco_open.jpg');?>" /></div>
<!-- 
                        <?php $owner_line = '[Add Owner]'; $owner_link = $this->baseUrl('/list/addOwner?id='.$property->id);
                              if ($owner != null) { $owner_line = 'About your host'; $owner_link = '';}?>
                        <h4><a href="<?php echo $owner_link;?>"><?php echo $owner_line;?></a></h4>
-->

                        <?php $owner_line = '[Add Owner]'; $owner_link = $this->baseUrl('/list/addOwner?id='.$property->id);
                        if ($owner != null) {	$owner_line = 'About your host';?>
                            <h4><?php echo $owner_line;?></h4> <?php } 
                        else { ?>
                            <h4><a href="<?php echo $owner_link;?>"><?php echo $owner_line;?></a></h4> <?php } ?>
                                                 
<!--                        
                         <?php if ($owner != null) { echo '<h4>About your host</h4>'; }
                               else { $owner_link=$this->baseUrl('/list/addOwner?id='.$property->id); 
                                 echo '<h4><a href='.$owner_link.'/>[Add Owner]</a></h4>'; } ?>
-->                        
                        <div style="margin-top:10px;" class="img_profle"><img src="<?php echo $this->baseUrl('/images/users/'.$owner_image);?>"/>
                            <p><?php echo $owner_name;?><!-- <br><span>31 October, 2011</span> --></p>
                        </div>
                        <div class="host_ratings">
                            <!--
                            <div>
                                <span>Response rate:</span>
                                <p>100% <div class="what"><img src="<?php echo $this->baseUrl('/images/btn_questin.jpg');?>" /></div></p>
                            </div>
                            <div>
                                <span>Acceptance rate:</span>
                                <p>100%<div  class="what"><img src="<?php echo $this->baseUrl('/images/btn_questin.jpg');?>" /></div></p>
                            </div>
                            <div>
                                <span>Verfied via Facebook</span>
                                <p>342 Friends</p>
                            </div>
                            -->
                        </div>
                            <div class="form_write_review">
                                <FORM id="send_message" action="#" method="post">
                                    <textarea cols="22" style="width:100%;" name="message" title="Got a question for this host?" rows="5" class="FrmtxtArea defaultText"></textarea><br>
                                    <input type="hidden" name="id" value="<?php echo $property->id;?>" />
                                    <input type="hidden" name="rating" value="<?php echo $this->user_rating;?>" />
                                </FORM>
                                <INPUT class="input" type="submit" onclick="submitForm('#send_message', ['message'], null);return false;" value="Send it now">
                            </div><!--form_write_review-->
                    </div>
                    <div class="l_price">
                        <div class="l_accordian_open"><a href="#"><img src="<?php echo $this->baseUrl('/images/btn_acco_open.jpg');?>" /></a></div>
                        <h4><a href="#">Other Listings</a></h4>
                    </div>
                </div>
            </div><!--right_side_panel ends here-->
            <div id="boxes">
                <div id="lb_login" style="height: 447px; width: 656px; background:none;" class="lb_window_zv">
                    <div class="close cboxClose2"></div>
                    <div id="lightbox_login" class="register">
                        <div class="form-section">
                            <div class="error_msg" style="width:100%;"></div>
                            <!-- <form method="post" id="register" name="register" action="#">  -->
                                <label for="username">Email address :<br /><input class="username" type="text" id="username" size="37" name="username" value=""/></label>
                                <label for="password">Password :<br /><input type="password" class="username" id="password" size="37" name="password"/></label>
                                <input class="login" type="submit" onclick="login('#username', '#password', '.error_msg');return false;" id="login" name="login" value=""/> 
                                <input class="cancel close" type="submit" onclick="return false;" value=""/>
                                <!-- <a href="#" class="close">Cancel</a> -->
                                <div class="btn_login_fb"><a href="#" onclick="login('','','.error_msg'); return false;"><img src="<?php echo $this->baseUrl('/images/btn_login_fb.jpg');?>" alt="Login Facebook" /></a></div>
                            <!-- </form> -->
                        </div>
                    </div>
                    <div class="lightbox_filter_action_area segment buttons">
                            
                    </div>
                </div>
            </div>
            <div id="boxes">
              <div id="lb_send_details" class="lb_window_zv" style="height: 100px; width: 300px; background:none;">
                <div class="close cboxClose3"></div>
                <div id="lb_show_form" class="register">
                <div class="form_write_review">
                <form id="send_details" action="#"> 
                    <label for="send_firstname">First Name:<br /><input class="username" type="text" id="firstname" size="37" name="firstname" value=""/></label>
                    <label for="send_lastname">Last Name:<br /><input class="username" type="text" id="lastname" size="37" name="lastname" value=""/></label>
                    <label for="send_email">Email Address:<br /><input class="username" type="text" id="email" size="37" name="email" value=""/></label>
                    <label for="send_phone">Home Phone:<br /><input class="username" type="text" id="phone" size="37" name="phone" value=""/></label>
                    <label for="send_checkin">Arrival Date:<br /><input class="defaultText checkin" title="<?php echo DATE_FORMAT;?>" type="text" size="37" name="check_in" value=""/></label>
                    <label for="send_checkout">Departure Date:<br /><input class="defaultText checkout" title="<?php echo DATE_FORMAT;?>" type="text" size="37" name="check_out" value=""/></label>
                    <label for="send_guests">Guests:<br /><input class="username" type="text" id="guests" size="37" name="guests" value=""/></label>
                    <textarea name="comments" title="Please write your questions here" style="width:100%;" cols="100" rows="5" class="FrmtxtArea defaultText"></textarea><br>
                    <input type="hidden" name="id" value="<?php echo $property->id;?>" />
                </form> 
                <input class="send" type="submit" onclick="submitForm('#send_details', ['check_in', 'check_out', 'guests'], '#lb_send_details'); return false;" value=""/>
                <input class="cancel close" type="submit" value=""/>
                </div>
                </div>
              </div>
            </div> 
            <div id="boxes">
                <div id="lb_thankyou" style="height: 200px; width: 400px; background:none;" class="lb_window_zv">
                    <div id="lb_show_msg" class="register">
                        <input class="ok close" type="submit" onclick="return false;" value=""/>
                    </div>
                    
                </div>
                <!-- <div class="close cboxClose"></div>  -->
            </div>
            <div id="mask_zv"></div>
<?php }?> <!-- End property detail available -->

