<p>
	<ul id="mostBookedCarousel" class="first-and-second-carousel jcarousel-skin-tango">
		<?php if (isset($this->error)) { ?>
			<p>An error was encountered in search.</p>
				<?php } elseif ($this->results != null) { ?>
					<?php $iCtr=0;   // REMOVE THIS LINE LATER once the api's are ready to provide the image file names ?>
					<?php foreach($this->results as $mostBookedData) : ?>	
						<li><img src="images/<?php echo ++$iCtr?>.jpg" height="70" width="110">
							<p>
							<?php 
								if( strlen($this->escape($mostBookedData['title'])) > VILLA_NAME_SMALL_SIZE )
									echo substr($this->escape($mostBookedData['title']),0,(VILLA_NAME_SMALL_SIZE-3)).'...';
								else
									echo $this->escape($mostBookedData['title']);
							?>
							</p>
							<span><img src="<?php echo $this->baseUrl();?>/images/symbl_rupee.jpg" alt="Indian Rupee" /><?php echo $this->escape(0+$mostBookedData['average_rate']);?></span>
						</li>
 					<?php endforeach; ?>
 				<?php } else {?>
			<p>No results were returned from search.</p>
		<?php } ?> 
	</ul>
</p>