<?php
$this->title = "Search Results";
$this->headTitle($this->title);
$mapHelper = $this->map();
?>

<?php if (isset($this->error)) { ?>
    <p>An error was encountered in search.</p>
 <?php } elseif ($this->results != null) {?>

<?php
// temp use of villaCtr - replace this later with number returned by search method
$villaCtr = ($this->page - 1) * $this->pagesz;
$mapStartNo = $villaCtr;
foreach($this->results as $result) : ?>
  <div class="search_result">
  <div class="search_no"> <?php echo ++$villaCtr ?></div>
  <!--search result number-->
  <?php
    $imagepath = $this->zvImage()->getFirstListingImage($this->baseUrl(), $result);
  ?>
  <div class="villa_image">  <img src="<?php echo $imagepath;?>" alt="resort name" />  </div>
  <!--picture-->
  <div class="favorite">  <img src="<?php echo $this->baseUrl();?>/images/icon_favorite.jpg" alt="Favorite" />  </div>
  <div class="resort_details">
  <h2><a href="<?php echo $this->baseUrl().'/list?id='.$result['id'];?>"><?php echo $this->escape($result['title']);?></a></h2>
  <p>
  <?php echo $this->escape($result['address__street_name']);?>,
  <?php echo $this->escape($result['address__city']);?>,
  <?php echo $this->escape($result['address__state']);?>
  <span><?php echo 'Guests: &nbsp'.$this->escape($result['guests']);?></span></p>
  <div class="reviews">  <p><?php echo $this->escape(0+$result['reviews']);?></p>  <span>Reviews</span>  </div>
  <div class="ratings">
  <!--golden and silver stars-->
  <ul>
  <?php for($rc=0; $rc < 5; $rc++) {
  if ((0+$result['rating']) > $rc) 
    echo '<li><img src="'.$this->baseUrl().'/images/icon_ratings_gold.jpg"/></li>';
  else
    echo '<li><img src="'.$this->baseUrl().'/images/icon_ratings_silver.jpg"/></li>';
  } ?>
  </ul>
  <span><?php echo $this->escape(0+$result['rating']);?> Ratings</span>
  </div>
  </div>
  <div class="price">
  <p>
  <img src="<?php echo $this->baseUrl();?>/images/symbl_rupee.jpg" alt="Rupee" /><?php echo $this->escape(0+$result['average_rate']);?>
  </p>
  <span>per night</span>
  <span>
    <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'edit', 'id'=>$result['id']));?>"> <img src="<?php echo $this->baseUrl();?>/images/icon_edit_pencil.jpg" alt="Edit" height="20" width="20"> </a> 
    <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'delete', 'id'=>$result['id']));?>"> <img src="<?php echo $this->baseUrl();?>/images/icon_delete_x.jpg" alt="Delete" height="20" width="20"> </a>
    </span> 
    </div><!--search_result1 ends here-->
  </div>
<?php endforeach; ?>
 <script type="text/javascript">
    <?php echo $mapHelper->setMapFromSearchResults($this->results, 'map');?>
 </script>

 <?php } else {?>
    <p>No results were returned from search.</p>
 <?php } ?>