<?php
$this->title = "Search Results";
$this->headTitle($this->title);
$mapHelper = $this->map();
?>

<?php if (isset($this->error)) { ?>
    <p>An error was encountered in search.</p>
 <?php } elseif ($this->results != null) {?>
 <table>
    <tr>
        <th>Type</th>
        <th>Rating</th>
        <th>Street</th>
        <th>City</th>
        <th>State</th>
        <th>Bedrooms</th>
        <th>Max Guests</th>
        <th>Rate</th>
        <th>Amenities</th>
        <th>&nbsp;</th>
    </tr>

  <?php foreach($this->results as $result) : ?>
        <tr>
            <td><?php echo $this->escape($result->type);?></td>
            <td><?php echo $this->escape($result->rating);?></td>
            <td><?php echo $this->escape($result->address__street_name);?></td>
            <td><?php echo $this->escape($result->address__city);?></td>
            <td><?php echo $this->escape($result->address__state);?></td>
            <td><?php echo $this->escape($result->bedrooms);?></td>
            <td><?php echo $this->escape($result->guests);?></td>
            <td><?php echo $this->escape($result->rate__daily);?></td>

        <?php $eoptions = $result->amenities;?>
            <td><?php if ($eoptions != null) { foreach ($eoptions as $v) { echo "$v<br/>"; } }?></td>
            <td> 
                <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'edit', 'id'=>$result->id));?>">Edit</a>
                <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'delete', 'id'=>$result->id));?>">Delete</a>
            </td>
        </tr>
  <?php endforeach; ?>
 </table>
 <?php if ($this->facets != null) {?>
    <?php $facet_str = ($this->facet_query == null) ? '' : $this->facet_query . ','?>
    <?php foreach($this->facets->getPropertyNames() as $facet): ?>
        <table border="1">
            <tr>
                <th scope="row"><?php echo $facet;?></th>
                <th></th>
            </tr>
            <?php foreach ($this->facets[$facet]->getPropertyNames() as $type): ?>
            <?php ?>
            <?php if (!in_array(substr($facet,0,-1).substr($type,0,-1), $this->facets_used)) {?>
                <tr>
                    <td><a href="<?php echo $this->url(array('controller'=>'search', 'action'=>'index', 'city'=>$this->search_query, 'facet'=>$facet_str . trim($facet).'='.trim($type)));?>"><?php echo $type;?></a></td>
                    <td><?php echo $this->facets[$facet][$type];?></td>
                </tr>
            <?php }?>
            <?php endforeach; ?>
        </table>
    <?php endforeach; ?>
<?php }?>
 <script type="text/javascript">
    <?php echo $mapHelper->setMapFromSearchResults($this->results, 'zvMapInfo');?>
 </script>

 <?php } else {?>
    <p>No results were returned from Search.</p>
 <?php } ?>