<?php
$this->title = "Search Results";
$this->headTitle($this->title);
$mapHelper = $this->map(); 
?>

<?php if (isset($this->error)) { ?>
    <p>An error was encountered in search.</p>
 <?php } elseif ($this->results != null) {?>
 <table>
    <tr>
        <th>Type</th>
        <th>Street</th>
        <th>City</th>
        <th>State</th>
        <th>Bedrooms</th>
        <th>Max Guests</th>
        <th>Amenities</th>
        <th>&nbsp;</th>
    </tr>

  <?php foreach($this->results as $result) : ?>
        <tr>
            <td><?php echo $this->escape($result->type);?></td>
            <td><?php echo $this->escape($result->address__street_name);?></td>
            <td><?php echo $this->escape($result->address__city);?></td>
            <td><?php echo $this->escape($result->address__state);?></td>
            <td><?php echo $this->escape($result->bedrooms);?></td>
            <td><?php echo $this->escape($result->guests);?></td>

        <?php $eoptions = $result->amenities;?>
            <td><?php if ($eoptions != null) { foreach ($eoptions as $v) { echo "$v<br/>"; } }?></td>
            <td> 
                <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'edit', 'id'=>$result->id));?>">Edit</a>
                <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'delete', 'id'=>$result->id));?>">Delete</a>
            </td>
        </tr>
  <?php endforeach; ?>
 </table>
 
 <script type="text/javascript">
    <?php echo $mapHelper->setMapFromSearchResults($this->results, 'zvMapInfo');?>
 </script>

 <?php } else {?>
    <p>No results were returned from Search.</p>
 <?php } ?>