<?php $baseUrl = $this->baseUrl();?>
<script type="text/javascript">
function getFacetValues()
{
	var features = ['shared', 'amenities', 'onsite_services', 'suitability', 'address__location'];
	for (var i in features) {
		   var feature = features[i];
		   $(".lbox_"+feature).children().remove();
		   $(".acc_section").find("[name='"+feature+"[]']").each(
				   function() {
					    var checked = $(this).is(':checked');
					    addCheckBox(feature, $(this).val(), $(this).next().text(), $(this).next().next().text(), checked);
				   });
	};
	
}
function addCheckBox(feature, name, label, value, checked) {
	
	var container = $(".lbox_"+feature);
	//alert(feature+','+name+','+label+','+value+','+checked);
	var checked_flag = '';
	if (checked) {
		checked_flag = 'checked="yes"';
	}
    var html = '<li class="clearfix"><input type="checkbox" id="lbox_'+feature+'" value="'+name+'" class="l_styled"' + checked_flag +'/>' +
               '<label>'+label+'</label> <span class="facet_count">'+value+'</span></li>';
    //alert(html);
    container.append(html);
}
</script>
<div class="l_refine_results v_refine_results">
    
	<div id="accordion">

    <h4><a href="#">Price</a></h4>
    <div class="acc_section">
        <div id="price_slider"></div>
        <p>
            <label style="margin-top:35px" for="price_range">Price range:</label>
            <input style="color:#0099CC;float:left;margin-top:-15px;background-color:#F5F5F5;border:none;" type="text" id="price_range" name="price_range" value="" style="border:0; color:#f6931f; font-weight:bold;" />
        </p>
    </div>
    
    <h4><a href="#">Room Type</a></h4>
    
    <div class="acc_section l_chkbox">
        <?php $feature = 'shared';
            $idcounter = 0;
            $no_checked = '';
            $yes_checked = '';
            if (isset($this->facets_selected[$feature])) {
                foreach($this->facets_selected[$feature] as $facet) {
                     if (preg_match("/\"?yes\"?/", $facet)) {
                         $yes_checked = 'checked="yes"';
                     }
                    if (preg_match("/\"?no\"?/", $facet)) {
                         $no_checked = 'checked="yes"';
                     }
                }
            }
        ?>
        <input type="checkbox" name="<?php echo $feature.'[]';?>" value="no" class="l_styled" <?php echo $no_checked;?> /><p>Entire home/villa</p>
        <?php if (isset($this->facets[$feature])) {?>
            <div class="l_room_nos"><?php echo $this->facets[$feature]['no'];?></div>
        <?php }?>
        
        <input type="checkbox" name="<?php echo $feature.'[]';?>" value="yes" class="l_styled" <?php echo $yes_checked;?>/><p>Shared</p>
        <?php if (isset($this->facets[$feature])) {?>
            <div class="l_room_nos"><?php echo $this->facets[$feature]['yes'];?></div>
        <?php }?>
    </div>
    
    <h4><a href="#">Amenities</a></h4>
    
    <div class="acc_section l_chkbox">
        <?php $feature = 'amenities';
              if (isset($this->facets[$feature])) {
                foreach ($this->facets[$feature]->getPropertyNames() as $type): 
                    $type = preg_replace('/[\x00-\x1F\x80-\xFF]/', '', $type);
                    $checked = '';
                    if (isset($this->facets_selected[$feature])) {
                        foreach($this->facets_selected[$feature] as $facet) {
                            if (preg_match("/\"?$type\"?/", $facet)) {
                                $checked = 'checked="yes"';
                                break;
                            }
                        } 
                    } 
        ?>
                    <input name="<?php echo $feature.'[]';?>" value="<?php echo $type;?>" type="checkbox" class="l_styled" <?php echo $checked;?>/><p><?php echo $type;?></p>
                    <div class="l_room_nos"><?php echo $this->facets[$feature][$type];?></div>
                 <?php endforeach; ?>
        <?php }?>        
    </div>
        
    <h4><a href="#">Onsite Services</a></h4>
    
    <div class="acc_section l_chkbox">
        <?php $feature = 'onsite_services';
              if (isset($this->facets[$feature])) {
                foreach ($this->facets[$feature]->getPropertyNames() as $type): 
                    $type = preg_replace('/[\x00-\x1F\x80-\xFF]/', '', $type);
                    $checked = '';
                    if (isset($this->facets_selected[$feature])) {
                        foreach($this->facets_selected[$feature] as $facet) {
                            if (preg_match("/\"?$type\"?/", $facet)) {
                                $checked = 'checked="yes"';
                                break;
                            }
                        }
                    } 
        ?>
                    <input name="<?php echo $feature.'[]';?>" value="<?php echo $type;?>" type="checkbox" class="l_styled" <?php echo $checked;?>/><p><?php echo $type;?></p>
                    <div class="l_room_nos"><?php echo $this->facets[$feature][$type];?></div>
                <?php endforeach; ?>
        <?php }?>        
    </div>
        
    <h4><a href="#">Suitability</a></h4>
    
    <div class="acc_section l_chkbox">
        <?php $feature = 'suitability';
              if (isset($this->facets[$feature])) {
                foreach ($this->facets[$feature]->getPropertyNames() as $type): 
                    $type = preg_replace('/[\x00-\x1F\x80-\xFF]/', '', $type);
                    $checked = '';
                    if (isset($this->facets_selected[$feature])) {
                        foreach($this->facets_selected[$feature] as $facet) {
                            if (preg_match("/\"?$type\"?/", $facet)) {
                                $checked = 'checked="yes"';
                                break;
                            }
                        }
                    } 
        ?>
                    <input name="<?php echo $feature.'[]';?>" value="<?php echo $type;?>" type="checkbox" class="l_styled" <?php echo $checked;?>/><p><?php echo $type;?></p>
                    <div class="l_room_nos"><?php echo $this->facets[$feature][$type];?></div>
                 <?php endforeach; ?>
        <?php }?>        
    </div>
    
    <h4><a href="#">Neighborhood</a></h4>
    
    <div class="acc_section l_chkbox">
        <?php $feature = 'address__location';
              $logger = Zend_Registry::get('zvlogger');
              if (isset($this->facets[$feature])) {
                foreach ($this->facets[$feature]->getPropertyNames() as $type): 
                    $type = preg_replace('/[\x00-\x1F\x80-\xFF]/', '', $type);
                    $checked = '';
                    if (isset($this->facets_selected[$feature])) {
                        foreach($this->facets_selected[$feature] as $facet) {
                            if (preg_match("/\"?$type\"?/", $facet)) {
                                $checked = 'checked="yes"';
                                break;
                            }
                        }
                    } 
        ?>
                    <?php if ($this->facets[$feature][$type] > 0) {?>
                        <input name="<?php echo $feature.'[]';?>" value="<?php echo $type;?>" type="checkbox" class="l_styled" <?php echo $checked;?>/><p><?php echo $type;?></p>
                        <div class="l_room_nos"><?php echo $this->facets[$feature][$type];?></div>
                    <?php }?>
                 <?php endforeach; ?>
        <?php }?>
    </div>
    
    <h4><a href="#">Keywords</a></h4>
        
    <div class="acc_section">
        <?php $keywords = isset($this->keywords) ? $this->keywords : ''; ?>
        <input class="defaultText" style="width:100%;" type="text" name="keywords" id="keywords" title="Enter Keywords"  value="<?php echo $keywords;?>"/>
    </div>
    
    </div>
    <input class="l_cta" style="float:left;margin:10px 0;" type="submit" onclick="validate();return true;" value="Refine Search"/> 
</div>

<div class="l_cta" style="margin-top:15px;clear:none;"><a href="#lb_search_zv" onclick="getFacetValues();" name="lightbox_zv">See more...</a></div>
<?php echo $this->render('search_lightbox.phtml');?>
