<div class="search_sort">
    <label for="guests">Sort by
        <select onchange="setPage(1); validate(); document.search_form.submit();" class="dropdwon_bg" id="sort" name="sort">
            <option id="select_r"  value="r" >Recommended</option>
            <option id="select_hl" value="hl">Rate (high to low)</option>
            <option id="select_lh" value="lh">Rate (low to high)</option>
        </select>
    </label>
</div>