<?php include_once("ZipVilla/TypeConstants.php");?>
<?php if (isset($this->error)) { ?>
    <p>An error was encountered in search.</p>
<?php } elseif ($this->results != null) {?>
<?php
    $villaCtr = ($this->page - 1) * $this->pagesz;
    foreach($this->results as $result) : ?>
        <?php 
            $street_name = isset($result['address__street_name']) ? $result['address__street_name'] : '';
            $city = isset($result['address__city']) ? $result['address__city'] : '';
            $state = isset($result['address__state']) ? $result['address__state'] : '';
            $title = isset($result['title']) ? $result['title'] : '';
            $guests = isset($result['guests']) ? $result['guests'] : 1;
            $reviews = isset($result['reviews']) ? $result['reviews'] : 0;
            $rating = isset($result['rating']) ? $result['rating'] : 1;
            $rate = isset($result['average_rate']) ? $result['average_rate'] : 0;
        ?>
        <div class="search_result">
            <div class="search_no"> <?php echo ++$villaCtr ?></div>
            <!--search result number-->
            <?php
                $imagepath = $this->zvImage()->getFirstListingImage($this->baseUrl(), $result);
                $link = $this->baseUrl('/list?id='.$result['id'].'&showtab='.TAB_LIST);
            ?>
            <div class="villa_image">  <a href="<?echo $link;?>"> <img src="<?php echo $imagepath;?>" alt="resort name" /></a>  
            </div>
            <!--picture-->
            <div class="favorite">  <img src="<?php echo $this->baseUrl();?>/images/icon_favorite.jpg" alt="Favorite" />  
            </div>
            <div class="resort_details">
                <h2><a href="<?php echo $link;?>"><?php echo $this->escape($title);?></a></h2>
                <p>
                    <?php echo $this->escape($street_name);?>,
                    <?php echo $this->escape($city);?>,
                    <?php echo $this->escape($state);?>
                    <span><?php echo 'Guests: &nbsp;'.$this->escape($guests);?></span>
                </p>
                <div class="reviews">  <p><?php echo $this->escape(0+$reviews);?></p>  <span>Reviews</span>  
                </div>
                <div class="ratings">
                    <!--golden and silver stars-->
                    <ul>
                    <?php for($rc=0; $rc < 5; $rc++) {
                        if ((0+$rating) > $rc) 
                            echo '<li><img src="'.$this->baseUrl().'/images/icon_ratings_gold.jpg"/></li>';
                        else
                            echo '<li><img src="'.$this->baseUrl().'/images/icon_ratings_silver.jpg"/></li>';
                        } ?>
                    </ul>
                </div>
            </div>
            <div class="price">
                <p>
                    <img src="<?php echo $this->baseUrl();?>/images/symbl_rupee.jpg" alt="Rupee" /><?php echo $this->escape(0+$rate);?>
                </p>
                <span>per night</span>
                <span>
                </span> 
            </div>
        </div>
    <?php endforeach; ?>
<?php } else {?>
    <p>No results were returned from search.</p>
<?php } ?>
